self-hosted-runner:
  labels:
    - ubicloud-standard-2
    - ubicloud-standard-4-arm

config-variables:
  - AWS_DEPLOY_ROLE_ARN
  - CI_DEBUG_SSH_WAIT_MINUTES
  - CI_RUNNER_GITHUB_HOSTED
  - CI_RUNNER_MANAGED_HEAVY
  - CI_RUNNER_MANAGED_LIGHT

config-secrets:
  - SSH_PUBLIC_KEY
