self-hosted-runner:
  labels:
    - ubicloud-standard-2
    - ubicloud-standard-4-arm

config-variables:
  - AWS_CAPTURE_ROLE_ARN
  - AWS_CI_CACHE_ROLE_ARN
  - AWS_CI_CACHE_PR_READONLY_ROLE_ARN
  - CI_DEBUG_SSH_WAIT_MINUTES
  - CI_RUNNER_GITHUB_HOSTED
  - CI_RUNNER_MANAGED_HEAVY
  - CI_RUNNER_MANAGED_LIGHT
  - JULES_SESSION_TIMEOUT_MINUTES
  - JULES_SESSIONS_ENDPOINT

config-secrets:
  - JULES_API_KEY
  - SSH_PUBLIC_KEY
