// Generated by `generate_decision_evidence_contract`; do not edit by hand.

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownProducer {
    EdgeTakerBlockedStrategyInput,
    EdgeTakerSubmitStrategyInput,
    OrderExecutionEntryIntent,
    OrderExecutionExitIntent,
    SubmitAdmissionAdmittedEntry,
    SubmitAdmissionRejectedEntry,
    SubmitAdmissionExit,
    SubmitAdmissionForcedReduction,
    BasketAdmissionGranted,
    BasketAdmissionRejected,
    CapitalAdmissionRebuild,
    SubmitReservationMetadata,
    SubmitReservationFill,
    EdgeTakerEntrySkip,
    EdgeTakerExitSubmitDecision,
    EdgeTakerExitHoldDecision,
    EdgeTakerExitEvaluation,
    SubmitAdmissionLossHalt,
    SubmitAdmissionOrderReject,
    OrderRejectObserverFeed,
    EdgeTakerOrderLifecycle,
    MakerRequoteThrottle,
    EdgeTakerSettlement,
    EdgeTakerBookingError,
    EdgeTakerTerminalSettlement,
    SubmitAdmissionVenueCaptureFailure,
    SubmitAdmissionVenueDivergence,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownPurpose {
    BlockedStrategyInputObservation,
    SubmitLinkedStrategyInputSnapshot,
    EntryOrderIntent,
    RiskReducingExitOrderIntent,
    AdmittedEntryAdmission,
    RejectedEntryAdmission,
    RiskReducingExitAdmission,
    ForcedReductionAdmission,
    BasketAdmissionGranted,
    BasketAdmissionRejected,
    CapitalAdmissionRebuild,
    SubmitReservationMetadata,
    SubmitReservationFill,
    EntrySkipObservation,
    ExitSubmissionDecision,
    ExitHoldDecision,
    ExitEvaluation,
    LossGovernorHalt,
    OrderReject,
    OrderLifecycle,
    RequoteThrottleObservation,
    Settlement,
    SettlementBookingError,
    TerminalSettlement,
    VenueTruthCaptureFailure,
    VenueTruthDivergence,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownIdentity {
    BlockedStrategyInputObservationV1,
    SubmitLinkedStrategyInputSnapshotV1,
    EntryOrderIntentV1,
    RiskReducingExitOrderIntentV1,
    AdmittedEntryAdmissionV1,
    RejectedEntryAdmissionV1,
    RiskReducingExitAdmissionV1,
    ForcedReductionAdmissionV1,
    BasketAdmissionGrantedV1,
    BasketAdmissionRejectedV1,
    CapitalAdmissionRebuildV1,
    SubmitReservationMetadataV1,
    SubmitReservationFillV1,
    EntrySkipObservationV1,
    ExitSubmissionDecisionV1,
    ExitHoldDecisionV1,
    ExitEvaluationV1,
    LossGovernorHaltV1,
    OrderRejectV1,
    OrderLifecycleV1,
    RequoteThrottleObservationV1,
    SettlementV1,
    SettlementBookingErrorV1,
    TerminalSettlementV1,
    VenueTruthCaptureFailureV1,
    VenueTruthDivergenceV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownDecodedFact {
    BlockedStrategyInputObservationV1,
    SubmitLinkedStrategyInputSnapshotV1,
    EntryOrderIntentV1,
    RiskReducingExitOrderIntentV1,
    AdmittedEntryAdmissionV1,
    RejectedEntryAdmissionV1,
    RiskReducingExitAdmissionV1,
    ForcedReductionAdmissionV1,
    BasketAdmissionGrantedV1,
    BasketAdmissionRejectedV1,
    CapitalAdmissionRebuildV1,
    SubmitReservationMetadataV1,
    SubmitReservationFillV1,
    EntrySkipObservationV1,
    ExitSubmissionDecisionV1,
    ExitHoldDecisionV1,
    ExitEvaluationV1,
    LossGovernorHaltV1,
    OrderRejectV1,
    OrderLifecycleV1,
    RequoteThrottleObservationV1,
    SettlementV1,
    SettlementBookingErrorV1,
    TerminalSettlementV1,
    VenueTruthCaptureFailureV1,
    VenueTruthDivergenceV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownConsumer {
    SubmitReservationRecoveryV1,
    SettlementRecoveryV1,
    BookingRecoveryV1,
    EntryChainProjectionV1,
    ShadowPnlV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownSink {
    Machine,
    Observation,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum EffectPolicy {
    MustPrecedeNewRisk,
    ObservationBoundedFailure,
    PreserveResult,
    ReconciliationFailClosed,
    RiskReducingContinues,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum KnownEventVariant {
    AdmittedEntry,
    BookingError,
    EntryIntent,
    Fill,
    Metadata,
    RejectedEntry,
    Settlement,
    Snapshot,
    TerminalSettlement,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ConsumerDisposition {
    Relevant(KnownEventVariant),
    Irrelevant,
}

mod producer_markers_sealed {
    pub trait Sealed {}
}
pub(crate) trait ProducerMarker: producer_markers_sealed::Sealed {}
pub(crate) mod producer_markers {
    pub(crate) struct EdgeTakerBlockedStrategyInput;
    pub(crate) struct EdgeTakerSubmitStrategyInput;
    pub(crate) struct OrderExecutionEntryIntent;
    pub(crate) struct OrderExecutionExitIntent;
    pub(crate) struct SubmitAdmissionAdmittedEntry;
    pub(crate) struct SubmitAdmissionRejectedEntry;
    pub(crate) struct SubmitAdmissionExit;
    pub(crate) struct SubmitAdmissionForcedReduction;
    pub(crate) struct BasketAdmissionGranted;
    pub(crate) struct BasketAdmissionRejected;
    pub(crate) struct CapitalAdmissionRebuild;
    pub(crate) struct SubmitReservationMetadata;
    pub(crate) struct SubmitReservationFill;
    pub(crate) struct EdgeTakerEntrySkip;
    pub(crate) struct EdgeTakerExitSubmitDecision;
    pub(crate) struct EdgeTakerExitHoldDecision;
    pub(crate) struct EdgeTakerExitEvaluation;
    pub(crate) struct SubmitAdmissionLossHalt;
    pub(crate) struct SubmitAdmissionOrderReject;
    pub(crate) struct OrderRejectObserverFeed;
    pub(crate) struct EdgeTakerOrderLifecycle;
    pub(crate) struct MakerRequoteThrottle;
    pub(crate) struct EdgeTakerSettlement;
    pub(crate) struct EdgeTakerBookingError;
    pub(crate) struct EdgeTakerTerminalSettlement;
    pub(crate) struct SubmitAdmissionVenueCaptureFailure;
    pub(crate) struct SubmitAdmissionVenueDivergence;
}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerBlockedStrategyInput {}
impl ProducerMarker for producer_markers::EdgeTakerBlockedStrategyInput {}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerSubmitStrategyInput {}
impl ProducerMarker for producer_markers::EdgeTakerSubmitStrategyInput {}
impl producer_markers_sealed::Sealed for producer_markers::OrderExecutionEntryIntent {}
impl ProducerMarker for producer_markers::OrderExecutionEntryIntent {}
impl producer_markers_sealed::Sealed for producer_markers::OrderExecutionExitIntent {}
impl ProducerMarker for producer_markers::OrderExecutionExitIntent {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitAdmissionAdmittedEntry {}
impl ProducerMarker for producer_markers::SubmitAdmissionAdmittedEntry {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitAdmissionRejectedEntry {}
impl ProducerMarker for producer_markers::SubmitAdmissionRejectedEntry {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitAdmissionExit {}
impl ProducerMarker for producer_markers::SubmitAdmissionExit {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitAdmissionForcedReduction {}
impl ProducerMarker for producer_markers::SubmitAdmissionForcedReduction {}
impl producer_markers_sealed::Sealed for producer_markers::BasketAdmissionGranted {}
impl ProducerMarker for producer_markers::BasketAdmissionGranted {}
impl producer_markers_sealed::Sealed for producer_markers::BasketAdmissionRejected {}
impl ProducerMarker for producer_markers::BasketAdmissionRejected {}
impl producer_markers_sealed::Sealed for producer_markers::CapitalAdmissionRebuild {}
impl ProducerMarker for producer_markers::CapitalAdmissionRebuild {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitReservationMetadata {}
impl ProducerMarker for producer_markers::SubmitReservationMetadata {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitReservationFill {}
impl ProducerMarker for producer_markers::SubmitReservationFill {}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerEntrySkip {}
impl ProducerMarker for producer_markers::EdgeTakerEntrySkip {}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerExitSubmitDecision {}
impl ProducerMarker for producer_markers::EdgeTakerExitSubmitDecision {}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerExitHoldDecision {}
impl ProducerMarker for producer_markers::EdgeTakerExitHoldDecision {}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerExitEvaluation {}
impl ProducerMarker for producer_markers::EdgeTakerExitEvaluation {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitAdmissionLossHalt {}
impl ProducerMarker for producer_markers::SubmitAdmissionLossHalt {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitAdmissionOrderReject {}
impl ProducerMarker for producer_markers::SubmitAdmissionOrderReject {}
impl producer_markers_sealed::Sealed for producer_markers::OrderRejectObserverFeed {}
impl ProducerMarker for producer_markers::OrderRejectObserverFeed {}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerOrderLifecycle {}
impl ProducerMarker for producer_markers::EdgeTakerOrderLifecycle {}
impl producer_markers_sealed::Sealed for producer_markers::MakerRequoteThrottle {}
impl ProducerMarker for producer_markers::MakerRequoteThrottle {}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerSettlement {}
impl ProducerMarker for producer_markers::EdgeTakerSettlement {}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerBookingError {}
impl ProducerMarker for producer_markers::EdgeTakerBookingError {}
impl producer_markers_sealed::Sealed for producer_markers::EdgeTakerTerminalSettlement {}
impl ProducerMarker for producer_markers::EdgeTakerTerminalSettlement {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitAdmissionVenueCaptureFailure {}
impl ProducerMarker for producer_markers::SubmitAdmissionVenueCaptureFailure {}
impl producer_markers_sealed::Sealed for producer_markers::SubmitAdmissionVenueDivergence {}
impl ProducerMarker for producer_markers::SubmitAdmissionVenueDivergence {}

mod purpose_markers_sealed {
    pub trait Sealed {}
}
pub(crate) trait PurposeMarker: purpose_markers_sealed::Sealed {}
pub(crate) mod purpose_markers {
    pub(crate) struct BlockedStrategyInputObservation;
    pub(crate) struct SubmitLinkedStrategyInputSnapshot;
    pub(crate) struct EntryOrderIntent;
    pub(crate) struct RiskReducingExitOrderIntent;
    pub(crate) struct AdmittedEntryAdmission;
    pub(crate) struct RejectedEntryAdmission;
    pub(crate) struct RiskReducingExitAdmission;
    pub(crate) struct ForcedReductionAdmission;
    pub(crate) struct BasketAdmissionGranted;
    pub(crate) struct BasketAdmissionRejected;
    pub(crate) struct CapitalAdmissionRebuild;
    pub(crate) struct SubmitReservationMetadata;
    pub(crate) struct SubmitReservationFill;
    pub(crate) struct EntrySkipObservation;
    pub(crate) struct ExitSubmissionDecision;
    pub(crate) struct ExitHoldDecision;
    pub(crate) struct ExitEvaluation;
    pub(crate) struct LossGovernorHalt;
    pub(crate) struct OrderReject;
    pub(crate) struct OrderLifecycle;
    pub(crate) struct RequoteThrottleObservation;
    pub(crate) struct Settlement;
    pub(crate) struct SettlementBookingError;
    pub(crate) struct TerminalSettlement;
    pub(crate) struct VenueTruthCaptureFailure;
    pub(crate) struct VenueTruthDivergence;
}
impl purpose_markers_sealed::Sealed for purpose_markers::BlockedStrategyInputObservation {}
impl PurposeMarker for purpose_markers::BlockedStrategyInputObservation {}
impl purpose_markers_sealed::Sealed for purpose_markers::SubmitLinkedStrategyInputSnapshot {}
impl PurposeMarker for purpose_markers::SubmitLinkedStrategyInputSnapshot {}
impl purpose_markers_sealed::Sealed for purpose_markers::EntryOrderIntent {}
impl PurposeMarker for purpose_markers::EntryOrderIntent {}
impl purpose_markers_sealed::Sealed for purpose_markers::RiskReducingExitOrderIntent {}
impl PurposeMarker for purpose_markers::RiskReducingExitOrderIntent {}
impl purpose_markers_sealed::Sealed for purpose_markers::AdmittedEntryAdmission {}
impl PurposeMarker for purpose_markers::AdmittedEntryAdmission {}
impl purpose_markers_sealed::Sealed for purpose_markers::RejectedEntryAdmission {}
impl PurposeMarker for purpose_markers::RejectedEntryAdmission {}
impl purpose_markers_sealed::Sealed for purpose_markers::RiskReducingExitAdmission {}
impl PurposeMarker for purpose_markers::RiskReducingExitAdmission {}
impl purpose_markers_sealed::Sealed for purpose_markers::ForcedReductionAdmission {}
impl PurposeMarker for purpose_markers::ForcedReductionAdmission {}
impl purpose_markers_sealed::Sealed for purpose_markers::BasketAdmissionGranted {}
impl PurposeMarker for purpose_markers::BasketAdmissionGranted {}
impl purpose_markers_sealed::Sealed for purpose_markers::BasketAdmissionRejected {}
impl PurposeMarker for purpose_markers::BasketAdmissionRejected {}
impl purpose_markers_sealed::Sealed for purpose_markers::CapitalAdmissionRebuild {}
impl PurposeMarker for purpose_markers::CapitalAdmissionRebuild {}
impl purpose_markers_sealed::Sealed for purpose_markers::SubmitReservationMetadata {}
impl PurposeMarker for purpose_markers::SubmitReservationMetadata {}
impl purpose_markers_sealed::Sealed for purpose_markers::SubmitReservationFill {}
impl PurposeMarker for purpose_markers::SubmitReservationFill {}
impl purpose_markers_sealed::Sealed for purpose_markers::EntrySkipObservation {}
impl PurposeMarker for purpose_markers::EntrySkipObservation {}
impl purpose_markers_sealed::Sealed for purpose_markers::ExitSubmissionDecision {}
impl PurposeMarker for purpose_markers::ExitSubmissionDecision {}
impl purpose_markers_sealed::Sealed for purpose_markers::ExitHoldDecision {}
impl PurposeMarker for purpose_markers::ExitHoldDecision {}
impl purpose_markers_sealed::Sealed for purpose_markers::ExitEvaluation {}
impl PurposeMarker for purpose_markers::ExitEvaluation {}
impl purpose_markers_sealed::Sealed for purpose_markers::LossGovernorHalt {}
impl PurposeMarker for purpose_markers::LossGovernorHalt {}
impl purpose_markers_sealed::Sealed for purpose_markers::OrderReject {}
impl PurposeMarker for purpose_markers::OrderReject {}
impl purpose_markers_sealed::Sealed for purpose_markers::OrderLifecycle {}
impl PurposeMarker for purpose_markers::OrderLifecycle {}
impl purpose_markers_sealed::Sealed for purpose_markers::RequoteThrottleObservation {}
impl PurposeMarker for purpose_markers::RequoteThrottleObservation {}
impl purpose_markers_sealed::Sealed for purpose_markers::Settlement {}
impl PurposeMarker for purpose_markers::Settlement {}
impl purpose_markers_sealed::Sealed for purpose_markers::SettlementBookingError {}
impl PurposeMarker for purpose_markers::SettlementBookingError {}
impl purpose_markers_sealed::Sealed for purpose_markers::TerminalSettlement {}
impl PurposeMarker for purpose_markers::TerminalSettlement {}
impl purpose_markers_sealed::Sealed for purpose_markers::VenueTruthCaptureFailure {}
impl PurposeMarker for purpose_markers::VenueTruthCaptureFailure {}
impl purpose_markers_sealed::Sealed for purpose_markers::VenueTruthDivergence {}
impl PurposeMarker for purpose_markers::VenueTruthDivergence {}

mod identity_markers_sealed {
    pub trait Sealed {}
}
pub(crate) trait IdentityMarker: identity_markers_sealed::Sealed {}
pub(crate) mod identity_markers {
    pub(crate) struct BlockedStrategyInputObservationV1;
    pub(crate) struct SubmitLinkedStrategyInputSnapshotV1;
    pub(crate) struct EntryOrderIntentV1;
    pub(crate) struct RiskReducingExitOrderIntentV1;
    pub(crate) struct AdmittedEntryAdmissionV1;
    pub(crate) struct RejectedEntryAdmissionV1;
    pub(crate) struct RiskReducingExitAdmissionV1;
    pub(crate) struct ForcedReductionAdmissionV1;
    pub(crate) struct BasketAdmissionGrantedV1;
    pub(crate) struct BasketAdmissionRejectedV1;
    pub(crate) struct CapitalAdmissionRebuildV1;
    pub(crate) struct SubmitReservationMetadataV1;
    pub(crate) struct SubmitReservationFillV1;
    pub(crate) struct EntrySkipObservationV1;
    pub(crate) struct ExitSubmissionDecisionV1;
    pub(crate) struct ExitHoldDecisionV1;
    pub(crate) struct ExitEvaluationV1;
    pub(crate) struct LossGovernorHaltV1;
    pub(crate) struct OrderRejectV1;
    pub(crate) struct OrderLifecycleV1;
    pub(crate) struct RequoteThrottleObservationV1;
    pub(crate) struct SettlementV1;
    pub(crate) struct SettlementBookingErrorV1;
    pub(crate) struct TerminalSettlementV1;
    pub(crate) struct VenueTruthCaptureFailureV1;
    pub(crate) struct VenueTruthDivergenceV1;
}
impl identity_markers_sealed::Sealed for identity_markers::BlockedStrategyInputObservationV1 {}
impl IdentityMarker for identity_markers::BlockedStrategyInputObservationV1 {}
impl identity_markers_sealed::Sealed for identity_markers::SubmitLinkedStrategyInputSnapshotV1 {}
impl IdentityMarker for identity_markers::SubmitLinkedStrategyInputSnapshotV1 {}
impl identity_markers_sealed::Sealed for identity_markers::EntryOrderIntentV1 {}
impl IdentityMarker for identity_markers::EntryOrderIntentV1 {}
impl identity_markers_sealed::Sealed for identity_markers::RiskReducingExitOrderIntentV1 {}
impl IdentityMarker for identity_markers::RiskReducingExitOrderIntentV1 {}
impl identity_markers_sealed::Sealed for identity_markers::AdmittedEntryAdmissionV1 {}
impl IdentityMarker for identity_markers::AdmittedEntryAdmissionV1 {}
impl identity_markers_sealed::Sealed for identity_markers::RejectedEntryAdmissionV1 {}
impl IdentityMarker for identity_markers::RejectedEntryAdmissionV1 {}
impl identity_markers_sealed::Sealed for identity_markers::RiskReducingExitAdmissionV1 {}
impl IdentityMarker for identity_markers::RiskReducingExitAdmissionV1 {}
impl identity_markers_sealed::Sealed for identity_markers::ForcedReductionAdmissionV1 {}
impl IdentityMarker for identity_markers::ForcedReductionAdmissionV1 {}
impl identity_markers_sealed::Sealed for identity_markers::BasketAdmissionGrantedV1 {}
impl IdentityMarker for identity_markers::BasketAdmissionGrantedV1 {}
impl identity_markers_sealed::Sealed for identity_markers::BasketAdmissionRejectedV1 {}
impl IdentityMarker for identity_markers::BasketAdmissionRejectedV1 {}
impl identity_markers_sealed::Sealed for identity_markers::CapitalAdmissionRebuildV1 {}
impl IdentityMarker for identity_markers::CapitalAdmissionRebuildV1 {}
impl identity_markers_sealed::Sealed for identity_markers::SubmitReservationMetadataV1 {}
impl IdentityMarker for identity_markers::SubmitReservationMetadataV1 {}
impl identity_markers_sealed::Sealed for identity_markers::SubmitReservationFillV1 {}
impl IdentityMarker for identity_markers::SubmitReservationFillV1 {}
impl identity_markers_sealed::Sealed for identity_markers::EntrySkipObservationV1 {}
impl IdentityMarker for identity_markers::EntrySkipObservationV1 {}
impl identity_markers_sealed::Sealed for identity_markers::ExitSubmissionDecisionV1 {}
impl IdentityMarker for identity_markers::ExitSubmissionDecisionV1 {}
impl identity_markers_sealed::Sealed for identity_markers::ExitHoldDecisionV1 {}
impl IdentityMarker for identity_markers::ExitHoldDecisionV1 {}
impl identity_markers_sealed::Sealed for identity_markers::ExitEvaluationV1 {}
impl IdentityMarker for identity_markers::ExitEvaluationV1 {}
impl identity_markers_sealed::Sealed for identity_markers::LossGovernorHaltV1 {}
impl IdentityMarker for identity_markers::LossGovernorHaltV1 {}
impl identity_markers_sealed::Sealed for identity_markers::OrderRejectV1 {}
impl IdentityMarker for identity_markers::OrderRejectV1 {}
impl identity_markers_sealed::Sealed for identity_markers::OrderLifecycleV1 {}
impl IdentityMarker for identity_markers::OrderLifecycleV1 {}
impl identity_markers_sealed::Sealed for identity_markers::RequoteThrottleObservationV1 {}
impl IdentityMarker for identity_markers::RequoteThrottleObservationV1 {}
impl identity_markers_sealed::Sealed for identity_markers::SettlementV1 {}
impl IdentityMarker for identity_markers::SettlementV1 {}
impl identity_markers_sealed::Sealed for identity_markers::SettlementBookingErrorV1 {}
impl IdentityMarker for identity_markers::SettlementBookingErrorV1 {}
impl identity_markers_sealed::Sealed for identity_markers::TerminalSettlementV1 {}
impl IdentityMarker for identity_markers::TerminalSettlementV1 {}
impl identity_markers_sealed::Sealed for identity_markers::VenueTruthCaptureFailureV1 {}
impl IdentityMarker for identity_markers::VenueTruthCaptureFailureV1 {}
impl identity_markers_sealed::Sealed for identity_markers::VenueTruthDivergenceV1 {}
impl IdentityMarker for identity_markers::VenueTruthDivergenceV1 {}

mod consumer_markers_sealed {
    pub trait Sealed {}
}
pub(crate) trait ConsumerMarker: consumer_markers_sealed::Sealed {}
pub(crate) mod consumer_markers {
    pub(crate) struct SubmitReservationRecoveryV1;
    pub(crate) struct SettlementRecoveryV1;
    pub(crate) struct BookingRecoveryV1;
    pub(crate) struct EntryChainProjectionV1;
    pub(crate) struct ShadowPnlV1;
}
impl consumer_markers_sealed::Sealed for consumer_markers::SubmitReservationRecoveryV1 {}
impl ConsumerMarker for consumer_markers::SubmitReservationRecoveryV1 {}
impl consumer_markers_sealed::Sealed for consumer_markers::SettlementRecoveryV1 {}
impl ConsumerMarker for consumer_markers::SettlementRecoveryV1 {}
impl consumer_markers_sealed::Sealed for consumer_markers::BookingRecoveryV1 {}
impl ConsumerMarker for consumer_markers::BookingRecoveryV1 {}
impl consumer_markers_sealed::Sealed for consumer_markers::EntryChainProjectionV1 {}
impl ConsumerMarker for consumer_markers::EntryChainProjectionV1 {}
impl consumer_markers_sealed::Sealed for consumer_markers::ShadowPnlV1 {}
impl ConsumerMarker for consumer_markers::ShadowPnlV1 {}

pub(crate) fn resolve_identity(kind: &str, schema_version: u32) -> anyhow::Result<KnownIdentity> {
    match (kind, schema_version) {
        ("blocked_strategy_input_observation", 1) => {
            Ok(KnownIdentity::BlockedStrategyInputObservationV1)
        }
        ("strategy_input_snapshot", 16) => Ok(KnownIdentity::SubmitLinkedStrategyInputSnapshotV1),
        ("order_intent", 16) => Ok(KnownIdentity::EntryOrderIntentV1),
        ("risk_reducing_exit_order_intent", 1) => Ok(KnownIdentity::RiskReducingExitOrderIntentV1),
        ("admission_decision", 16) => Ok(KnownIdentity::AdmittedEntryAdmissionV1),
        ("rejected_entry_admission", 1) => Ok(KnownIdentity::RejectedEntryAdmissionV1),
        ("risk_reducing_exit_admission", 1) => Ok(KnownIdentity::RiskReducingExitAdmissionV1),
        ("forced_reduction_admission", 1) => Ok(KnownIdentity::ForcedReductionAdmissionV1),
        ("basket_admission_granted", 1) => Ok(KnownIdentity::BasketAdmissionGrantedV1),
        ("basket_admission_rejected", 1) => Ok(KnownIdentity::BasketAdmissionRejectedV1),
        ("capital_admission_rebuild", 16) => Ok(KnownIdentity::CapitalAdmissionRebuildV1),
        ("submit_reservation_metadata", 16) => Ok(KnownIdentity::SubmitReservationMetadataV1),
        ("submit_reservation_fill", 16) => Ok(KnownIdentity::SubmitReservationFillV1),
        ("entry_skip", 16) => Ok(KnownIdentity::EntrySkipObservationV1),
        ("exit_submission_decision", 1) => Ok(KnownIdentity::ExitSubmissionDecisionV1),
        ("exit_hold_decision", 1) => Ok(KnownIdentity::ExitHoldDecisionV1),
        ("exit_evaluation", 16) => Ok(KnownIdentity::ExitEvaluationV1),
        ("loss_governor_halt", 16) => Ok(KnownIdentity::LossGovernorHaltV1),
        ("order_reject", 16) => Ok(KnownIdentity::OrderRejectV1),
        ("order_lifecycle", 16) => Ok(KnownIdentity::OrderLifecycleV1),
        ("requote_throttle", 16) => Ok(KnownIdentity::RequoteThrottleObservationV1),
        ("settlement", 16) => Ok(KnownIdentity::SettlementV1),
        ("settlement_booking_error", 16) => Ok(KnownIdentity::SettlementBookingErrorV1),
        ("terminal_settlement", 16) => Ok(KnownIdentity::TerminalSettlementV1),
        ("venue_truth_capture_failure", 16) => Ok(KnownIdentity::VenueTruthCaptureFailureV1),
        ("venue_truth_divergence", 16) => Ok(KnownIdentity::VenueTruthDivergenceV1),
        _ => Err(anyhow::anyhow!(
            "unregistered decision-evidence identity (`{kind}`, {schema_version})"
        )),
    }
}

pub(crate) const fn purpose_for_producer(producer: KnownProducer) -> KnownPurpose {
    match producer {
        KnownProducer::EdgeTakerBlockedStrategyInput => {
            KnownPurpose::BlockedStrategyInputObservation
        }
        KnownProducer::EdgeTakerSubmitStrategyInput => {
            KnownPurpose::SubmitLinkedStrategyInputSnapshot
        }
        KnownProducer::OrderExecutionEntryIntent => KnownPurpose::EntryOrderIntent,
        KnownProducer::OrderExecutionExitIntent => KnownPurpose::RiskReducingExitOrderIntent,
        KnownProducer::SubmitAdmissionAdmittedEntry => KnownPurpose::AdmittedEntryAdmission,
        KnownProducer::SubmitAdmissionRejectedEntry => KnownPurpose::RejectedEntryAdmission,
        KnownProducer::SubmitAdmissionExit => KnownPurpose::RiskReducingExitAdmission,
        KnownProducer::SubmitAdmissionForcedReduction => KnownPurpose::ForcedReductionAdmission,
        KnownProducer::BasketAdmissionGranted => KnownPurpose::BasketAdmissionGranted,
        KnownProducer::BasketAdmissionRejected => KnownPurpose::BasketAdmissionRejected,
        KnownProducer::CapitalAdmissionRebuild => KnownPurpose::CapitalAdmissionRebuild,
        KnownProducer::SubmitReservationMetadata => KnownPurpose::SubmitReservationMetadata,
        KnownProducer::SubmitReservationFill => KnownPurpose::SubmitReservationFill,
        KnownProducer::EdgeTakerEntrySkip => KnownPurpose::EntrySkipObservation,
        KnownProducer::EdgeTakerExitSubmitDecision => KnownPurpose::ExitSubmissionDecision,
        KnownProducer::EdgeTakerExitHoldDecision => KnownPurpose::ExitHoldDecision,
        KnownProducer::EdgeTakerExitEvaluation => KnownPurpose::ExitEvaluation,
        KnownProducer::SubmitAdmissionLossHalt => KnownPurpose::LossGovernorHalt,
        KnownProducer::SubmitAdmissionOrderReject => KnownPurpose::OrderReject,
        KnownProducer::OrderRejectObserverFeed => KnownPurpose::OrderReject,
        KnownProducer::EdgeTakerOrderLifecycle => KnownPurpose::OrderLifecycle,
        KnownProducer::MakerRequoteThrottle => KnownPurpose::RequoteThrottleObservation,
        KnownProducer::EdgeTakerSettlement => KnownPurpose::Settlement,
        KnownProducer::EdgeTakerBookingError => KnownPurpose::SettlementBookingError,
        KnownProducer::EdgeTakerTerminalSettlement => KnownPurpose::TerminalSettlement,
        KnownProducer::SubmitAdmissionVenueCaptureFailure => KnownPurpose::VenueTruthCaptureFailure,
        KnownProducer::SubmitAdmissionVenueDivergence => KnownPurpose::VenueTruthDivergence,
    }
}

pub(crate) const fn current_identity_for_purpose(purpose: KnownPurpose) -> KnownIdentity {
    match purpose {
        KnownPurpose::BlockedStrategyInputObservation => {
            KnownIdentity::BlockedStrategyInputObservationV1
        }
        KnownPurpose::SubmitLinkedStrategyInputSnapshot => {
            KnownIdentity::SubmitLinkedStrategyInputSnapshotV1
        }
        KnownPurpose::EntryOrderIntent => KnownIdentity::EntryOrderIntentV1,
        KnownPurpose::RiskReducingExitOrderIntent => KnownIdentity::RiskReducingExitOrderIntentV1,
        KnownPurpose::AdmittedEntryAdmission => KnownIdentity::AdmittedEntryAdmissionV1,
        KnownPurpose::RejectedEntryAdmission => KnownIdentity::RejectedEntryAdmissionV1,
        KnownPurpose::RiskReducingExitAdmission => KnownIdentity::RiskReducingExitAdmissionV1,
        KnownPurpose::ForcedReductionAdmission => KnownIdentity::ForcedReductionAdmissionV1,
        KnownPurpose::BasketAdmissionGranted => KnownIdentity::BasketAdmissionGrantedV1,
        KnownPurpose::BasketAdmissionRejected => KnownIdentity::BasketAdmissionRejectedV1,
        KnownPurpose::CapitalAdmissionRebuild => KnownIdentity::CapitalAdmissionRebuildV1,
        KnownPurpose::SubmitReservationMetadata => KnownIdentity::SubmitReservationMetadataV1,
        KnownPurpose::SubmitReservationFill => KnownIdentity::SubmitReservationFillV1,
        KnownPurpose::EntrySkipObservation => KnownIdentity::EntrySkipObservationV1,
        KnownPurpose::ExitSubmissionDecision => KnownIdentity::ExitSubmissionDecisionV1,
        KnownPurpose::ExitHoldDecision => KnownIdentity::ExitHoldDecisionV1,
        KnownPurpose::ExitEvaluation => KnownIdentity::ExitEvaluationV1,
        KnownPurpose::LossGovernorHalt => KnownIdentity::LossGovernorHaltV1,
        KnownPurpose::OrderReject => KnownIdentity::OrderRejectV1,
        KnownPurpose::OrderLifecycle => KnownIdentity::OrderLifecycleV1,
        KnownPurpose::RequoteThrottleObservation => KnownIdentity::RequoteThrottleObservationV1,
        KnownPurpose::Settlement => KnownIdentity::SettlementV1,
        KnownPurpose::SettlementBookingError => KnownIdentity::SettlementBookingErrorV1,
        KnownPurpose::TerminalSettlement => KnownIdentity::TerminalSettlementV1,
        KnownPurpose::VenueTruthCaptureFailure => KnownIdentity::VenueTruthCaptureFailureV1,
        KnownPurpose::VenueTruthDivergence => KnownIdentity::VenueTruthDivergenceV1,
    }
}

pub(crate) const fn sink_for_purpose(purpose: KnownPurpose) -> KnownSink {
    match purpose {
        KnownPurpose::BlockedStrategyInputObservation => KnownSink::Observation,
        KnownPurpose::SubmitLinkedStrategyInputSnapshot => KnownSink::Machine,
        KnownPurpose::EntryOrderIntent => KnownSink::Machine,
        KnownPurpose::RiskReducingExitOrderIntent => KnownSink::Machine,
        KnownPurpose::AdmittedEntryAdmission => KnownSink::Machine,
        KnownPurpose::RejectedEntryAdmission => KnownSink::Machine,
        KnownPurpose::RiskReducingExitAdmission => KnownSink::Machine,
        KnownPurpose::ForcedReductionAdmission => KnownSink::Machine,
        KnownPurpose::BasketAdmissionGranted => KnownSink::Machine,
        KnownPurpose::BasketAdmissionRejected => KnownSink::Machine,
        KnownPurpose::CapitalAdmissionRebuild => KnownSink::Machine,
        KnownPurpose::SubmitReservationMetadata => KnownSink::Machine,
        KnownPurpose::SubmitReservationFill => KnownSink::Machine,
        KnownPurpose::EntrySkipObservation => KnownSink::Observation,
        KnownPurpose::ExitSubmissionDecision => KnownSink::Machine,
        KnownPurpose::ExitHoldDecision => KnownSink::Observation,
        KnownPurpose::ExitEvaluation => KnownSink::Observation,
        KnownPurpose::LossGovernorHalt => KnownSink::Machine,
        KnownPurpose::OrderReject => KnownSink::Machine,
        KnownPurpose::OrderLifecycle => KnownSink::Machine,
        KnownPurpose::RequoteThrottleObservation => KnownSink::Observation,
        KnownPurpose::Settlement => KnownSink::Machine,
        KnownPurpose::SettlementBookingError => KnownSink::Machine,
        KnownPurpose::TerminalSettlement => KnownSink::Machine,
        KnownPurpose::VenueTruthCaptureFailure => KnownSink::Machine,
        KnownPurpose::VenueTruthDivergence => KnownSink::Machine,
    }
}

pub(crate) const fn effect_policy_for_purpose(purpose: KnownPurpose) -> EffectPolicy {
    match purpose {
        KnownPurpose::BlockedStrategyInputObservation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::SubmitLinkedStrategyInputSnapshot => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::EntryOrderIntent => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::RiskReducingExitOrderIntent => EffectPolicy::RiskReducingContinues,
        KnownPurpose::AdmittedEntryAdmission => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::RejectedEntryAdmission => EffectPolicy::PreserveResult,
        KnownPurpose::RiskReducingExitAdmission => EffectPolicy::RiskReducingContinues,
        KnownPurpose::ForcedReductionAdmission => EffectPolicy::RiskReducingContinues,
        KnownPurpose::BasketAdmissionGranted => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::BasketAdmissionRejected => EffectPolicy::PreserveResult,
        KnownPurpose::CapitalAdmissionRebuild => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::SubmitReservationMetadata => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::SubmitReservationFill => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::EntrySkipObservation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::ExitSubmissionDecision => EffectPolicy::RiskReducingContinues,
        KnownPurpose::ExitHoldDecision => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::ExitEvaluation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::LossGovernorHalt => EffectPolicy::PreserveResult,
        KnownPurpose::OrderReject => EffectPolicy::PreserveResult,
        KnownPurpose::OrderLifecycle => EffectPolicy::PreserveResult,
        KnownPurpose::RequoteThrottleObservation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::Settlement => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::SettlementBookingError => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::TerminalSettlement => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::VenueTruthCaptureFailure => EffectPolicy::RiskReducingContinues,
        KnownPurpose::VenueTruthDivergence => EffectPolicy::PreserveResult,
    }
}

pub(crate) const fn facts_for_identity(identity: KnownIdentity) -> &'static [KnownDecodedFact] {
    match identity {
        KnownIdentity::BlockedStrategyInputObservationV1 => {
            &[KnownDecodedFact::BlockedStrategyInputObservationV1]
        }
        KnownIdentity::SubmitLinkedStrategyInputSnapshotV1 => {
            &[KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1]
        }
        KnownIdentity::EntryOrderIntentV1 => &[KnownDecodedFact::EntryOrderIntentV1],
        KnownIdentity::RiskReducingExitOrderIntentV1 => {
            &[KnownDecodedFact::RiskReducingExitOrderIntentV1]
        }
        KnownIdentity::AdmittedEntryAdmissionV1 => &[KnownDecodedFact::AdmittedEntryAdmissionV1],
        KnownIdentity::RejectedEntryAdmissionV1 => &[KnownDecodedFact::RejectedEntryAdmissionV1],
        KnownIdentity::RiskReducingExitAdmissionV1 => {
            &[KnownDecodedFact::RiskReducingExitAdmissionV1]
        }
        KnownIdentity::ForcedReductionAdmissionV1 => {
            &[KnownDecodedFact::ForcedReductionAdmissionV1]
        }
        KnownIdentity::BasketAdmissionGrantedV1 => &[KnownDecodedFact::BasketAdmissionGrantedV1],
        KnownIdentity::BasketAdmissionRejectedV1 => &[KnownDecodedFact::BasketAdmissionRejectedV1],
        KnownIdentity::CapitalAdmissionRebuildV1 => &[KnownDecodedFact::CapitalAdmissionRebuildV1],
        KnownIdentity::SubmitReservationMetadataV1 => {
            &[KnownDecodedFact::SubmitReservationMetadataV1]
        }
        KnownIdentity::SubmitReservationFillV1 => &[KnownDecodedFact::SubmitReservationFillV1],
        KnownIdentity::EntrySkipObservationV1 => &[KnownDecodedFact::EntrySkipObservationV1],
        KnownIdentity::ExitSubmissionDecisionV1 => &[KnownDecodedFact::ExitSubmissionDecisionV1],
        KnownIdentity::ExitHoldDecisionV1 => &[KnownDecodedFact::ExitHoldDecisionV1],
        KnownIdentity::ExitEvaluationV1 => &[KnownDecodedFact::ExitEvaluationV1],
        KnownIdentity::LossGovernorHaltV1 => &[KnownDecodedFact::LossGovernorHaltV1],
        KnownIdentity::OrderRejectV1 => &[KnownDecodedFact::OrderRejectV1],
        KnownIdentity::OrderLifecycleV1 => &[KnownDecodedFact::OrderLifecycleV1],
        KnownIdentity::RequoteThrottleObservationV1 => {
            &[KnownDecodedFact::RequoteThrottleObservationV1]
        }
        KnownIdentity::SettlementV1 => &[KnownDecodedFact::SettlementV1],
        KnownIdentity::SettlementBookingErrorV1 => &[KnownDecodedFact::SettlementBookingErrorV1],
        KnownIdentity::TerminalSettlementV1 => &[KnownDecodedFact::TerminalSettlementV1],
        KnownIdentity::VenueTruthCaptureFailureV1 => {
            &[KnownDecodedFact::VenueTruthCaptureFailureV1]
        }
        KnownIdentity::VenueTruthDivergenceV1 => &[KnownDecodedFact::VenueTruthDivergenceV1],
    }
}

pub(crate) const fn identity_metadata(
    identity: KnownIdentity,
) -> (&'static str, u32, &'static str, &'static str) {
    match identity {
        KnownIdentity::BlockedStrategyInputObservationV1 => (
            "blocked_strategy_input_observation",
            1,
            "bolt_v3.strategy_input_snapshot",
            "blocked_strategy_input_observation",
        ),
        KnownIdentity::SubmitLinkedStrategyInputSnapshotV1 => (
            "strategy_input_snapshot",
            16,
            "bolt_v3.strategy_input_snapshot",
            "snapshot",
        ),
        KnownIdentity::EntryOrderIntentV1 => ("order_intent", 16, "bolt_v3.order_intent", "intent"),
        KnownIdentity::RiskReducingExitOrderIntentV1 => (
            "risk_reducing_exit_order_intent",
            1,
            "bolt_v3.order_intent",
            "intent",
        ),
        KnownIdentity::AdmittedEntryAdmissionV1 => (
            "admission_decision",
            16,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::RejectedEntryAdmissionV1 => (
            "rejected_entry_admission",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::RiskReducingExitAdmissionV1 => (
            "risk_reducing_exit_admission",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::ForcedReductionAdmissionV1 => (
            "forced_reduction_admission",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::BasketAdmissionGrantedV1 => (
            "basket_admission_granted",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::BasketAdmissionRejectedV1 => (
            "basket_admission_rejected",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::CapitalAdmissionRebuildV1 => (
            "capital_admission_rebuild",
            16,
            "bolt_v3.capital_admission_rebuild",
            "audit",
        ),
        KnownIdentity::SubmitReservationMetadataV1 => (
            "submit_reservation_metadata",
            16,
            "bolt_v3.submit_admission",
            "metadata",
        ),
        KnownIdentity::SubmitReservationFillV1 => (
            "submit_reservation_fill",
            16,
            "bolt_v3.submit_admission",
            "fill",
        ),
        KnownIdentity::EntrySkipObservationV1 => {
            ("entry_skip", 16, "bolt_v3.entry_skip", "entry_skip")
        }
        KnownIdentity::ExitSubmissionDecisionV1 => (
            "exit_submission_decision",
            1,
            "bolt_v3.exit_decision",
            "exit_decision",
        ),
        KnownIdentity::ExitHoldDecisionV1 => (
            "exit_hold_decision",
            1,
            "bolt_v3.exit_decision",
            "exit_decision",
        ),
        KnownIdentity::ExitEvaluationV1 => (
            "exit_evaluation",
            16,
            "bolt_v3.exit_evaluation",
            "exit_evaluation",
        ),
        KnownIdentity::LossGovernorHaltV1 => (
            "loss_governor_halt",
            16,
            "bolt_v3.loss_governor_halt",
            "loss_governor_halt",
        ),
        KnownIdentity::OrderRejectV1 => {
            ("order_reject", 16, "bolt_v3.order_reject", "order_reject")
        }
        KnownIdentity::OrderLifecycleV1 => (
            "order_lifecycle",
            16,
            "bolt_v3.order_lifecycle",
            "order_lifecycle",
        ),
        KnownIdentity::RequoteThrottleObservationV1 => (
            "requote_throttle",
            16,
            "bolt_v3.requote_throttle",
            "requote_throttle",
        ),
        KnownIdentity::SettlementV1 => ("settlement", 16, "bolt_v3.settlement", "settlement"),
        KnownIdentity::SettlementBookingErrorV1 => (
            "settlement_booking_error",
            16,
            "bolt_v3.settlement",
            "settlement_booking_error",
        ),
        KnownIdentity::TerminalSettlementV1 => (
            "terminal_settlement",
            16,
            "bolt_v3.settlement",
            "terminal_settlement",
        ),
        KnownIdentity::VenueTruthCaptureFailureV1 => (
            "venue_truth_capture_failure",
            16,
            "bolt_v3.venue_truth_capture_failure",
            "venue_truth_capture_failure",
        ),
        KnownIdentity::VenueTruthDivergenceV1 => (
            "venue_truth_divergence",
            16,
            "bolt_v3.venue_truth_divergence",
            "venue_truth_divergence",
        ),
    }
}

pub(crate) const fn disposition(
    fact: KnownDecodedFact,
    consumer: KnownConsumer,
) -> ConsumerDisposition {
    match (fact, consumer) {
        (
            KnownDecodedFact::BlockedStrategyInputObservationV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (
            KnownDecodedFact::BlockedStrategyInputObservationV1,
            KnownConsumer::SettlementRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::BlockedStrategyInputObservationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::BlockedStrategyInputObservationV1,
            KnownConsumer::EntryChainProjectionV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::BlockedStrategyInputObservationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (
            KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1,
            KnownConsumer::SettlementRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (
            KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1,
            KnownConsumer::BookingRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (
            KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1,
            KnownConsumer::EntryChainProjectionV1,
        ) => ConsumerDisposition::Relevant(KnownEventVariant::Snapshot),
        (KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::Snapshot)
        }
        (KnownDecodedFact::EntryOrderIntentV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntryOrderIntentV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntryOrderIntentV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntryOrderIntentV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::EntryIntent)
        }
        (KnownDecodedFact::EntryOrderIntentV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::EntryIntent)
        }
        (
            KnownDecodedFact::RiskReducingExitOrderIntentV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::RiskReducingExitOrderIntentV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RiskReducingExitOrderIntentV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::RiskReducingExitOrderIntentV1,
            KnownConsumer::EntryChainProjectionV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::RiskReducingExitOrderIntentV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::AdmittedEntryAdmissionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::AdmittedEntryAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::AdmittedEntryAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::AdmittedEntryAdmissionV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::AdmittedEntry)
        }
        (KnownDecodedFact::AdmittedEntryAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::AdmittedEntry)
        }
        (
            KnownDecodedFact::RejectedEntryAdmissionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::RejectedEntryAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RejectedEntryAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RejectedEntryAdmissionV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::RejectedEntry)
        }
        (KnownDecodedFact::RejectedEntryAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::RiskReducingExitAdmissionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::RiskReducingExitAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RiskReducingExitAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RiskReducingExitAdmissionV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RiskReducingExitAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::ForcedReductionAdmissionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::ForcedReductionAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ForcedReductionAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ForcedReductionAdmissionV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ForcedReductionAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::BasketAdmissionGrantedV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::BasketAdmissionGrantedV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionGrantedV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionGrantedV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionGrantedV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::BasketAdmissionRejectedV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::BasketAdmissionRejectedV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionRejectedV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionRejectedV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionRejectedV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::CapitalAdmissionRebuildV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::CapitalAdmissionRebuildV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::CapitalAdmissionRebuildV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::CapitalAdmissionRebuildV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::CapitalAdmissionRebuildV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::SubmitReservationMetadataV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Relevant(KnownEventVariant::Metadata),
        (KnownDecodedFact::SubmitReservationMetadataV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationMetadataV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationMetadataV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationMetadataV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationFillV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::Fill)
        }
        (KnownDecodedFact::SubmitReservationFillV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationFillV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationFillV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationFillV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntrySkipObservationV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntrySkipObservationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntrySkipObservationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntrySkipObservationV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntrySkipObservationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::ExitSubmissionDecisionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::ExitSubmissionDecisionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitSubmissionDecisionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitSubmissionDecisionV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitSubmissionDecisionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitHoldDecisionV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitHoldDecisionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitHoldDecisionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitHoldDecisionV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitHoldDecisionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitEvaluationV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitEvaluationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitEvaluationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitEvaluationV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitEvaluationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::LossGovernorHaltV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::LossGovernorHaltV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::LossGovernorHaltV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::LossGovernorHaltV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::LossGovernorHaltV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderRejectV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderRejectV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderRejectV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderRejectV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderRejectV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderLifecycleV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderLifecycleV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderLifecycleV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderLifecycleV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderLifecycleV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::RequoteThrottleObservationV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::RequoteThrottleObservationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RequoteThrottleObservationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RequoteThrottleObservationV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RequoteThrottleObservationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::Settlement)
        }
        (KnownDecodedFact::SettlementV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::SettlementBookingErrorV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::SettlementBookingErrorV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementBookingErrorV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::BookingError)
        }
        (KnownDecodedFact::SettlementBookingErrorV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementBookingErrorV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::TerminalSettlementV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::TerminalSettlementV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::TerminalSettlementV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Relevant(KnownEventVariant::TerminalSettlement)
        }
        (KnownDecodedFact::TerminalSettlementV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::TerminalSettlementV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::VenueTruthCaptureFailureV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::VenueTruthCaptureFailureV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthCaptureFailureV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthCaptureFailureV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthCaptureFailureV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthDivergenceV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthDivergenceV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthDivergenceV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthDivergenceV1, KnownConsumer::EntryChainProjectionV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthDivergenceV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
    }
}
