// Generated by `generate_decision_evidence_contract`; do not edit by hand.

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownPurpose {
    BlockedStrategyInputObservation,
    SubmitLinkedStrategyInputSnapshot,
    EntryOrderIntent,
    RiskReducingExitOrderIntent,
    AdmittedEntryAdmission,
    RejectedEntryAdmission,
    RiskReducingExitAdmission,
    ForcedReductionAdmission,
    BasketAdmissionGranted,
    BasketAdmissionRejected,
    CapitalAdmissionRebuild,
    SubmitReservationMetadata,
    SubmitReservationFill,
    EntrySkipObservation,
    ExitSubmissionDecision,
    ExitHoldDecision,
    ExitEvaluation,
    LossGovernorHalt,
    OrderReject,
    OrderLifecycle,
    RequoteThrottleObservation,
    Settlement,
    SettlementBookingError,
    TerminalSettlement,
    VenueTruthCaptureFailure,
    VenueTruthDivergence,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownIdentity {
    BlockedStrategyInputObservationV1,
    SubmitLinkedStrategyInputSnapshotV1,
    EntryOrderIntentV1,
    RiskReducingExitOrderIntentV1,
    AdmittedEntryAdmissionV1,
    RejectedEntryAdmissionV1,
    RiskReducingExitAdmissionV1,
    ForcedReductionAdmissionV1,
    BasketAdmissionGrantedV1,
    BasketAdmissionRejectedV1,
    CapitalAdmissionRebuildV1,
    SubmitReservationMetadataV1,
    SubmitReservationFillV1,
    EntrySkipObservationV1,
    ExitSubmissionDecisionV1,
    ExitHoldDecisionV1,
    ExitEvaluationV1,
    LossGovernorHaltV1,
    OrderRejectV1,
    OrderLifecycleV1,
    RequoteThrottleObservationV1,
    SettlementV1,
    SettlementBookingErrorV1,
    TerminalSettlementV1,
    VenueTruthCaptureFailureV1,
    VenueTruthDivergenceV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownDecodedFact {
    BlockedStrategyInputObservationV1,
    SubmitLinkedStrategyInputSnapshotV1,
    EntryOrderIntentV1,
    RiskReducingExitOrderIntentV1,
    AdmittedEntryAdmissionV1,
    RejectedEntryAdmissionV1,
    RiskReducingExitAdmissionV1,
    ForcedReductionAdmissionV1,
    BasketAdmissionGrantedV1,
    BasketAdmissionRejectedV1,
    CapitalAdmissionRebuildV1,
    SubmitReservationMetadataV1,
    SubmitReservationFillV1,
    EntrySkipObservationV1,
    ExitSubmissionDecisionV1,
    ExitHoldDecisionV1,
    ExitEvaluationV1,
    LossGovernorHaltV1,
    OrderRejectV1,
    OrderLifecycleV1,
    RequoteThrottleObservationV1,
    SettlementV1,
    SettlementBookingErrorV1,
    TerminalSettlementV1,
    VenueTruthCaptureFailureV1,
    VenueTruthDivergenceV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownConsumer {
    SubmitReservationRecoveryV1,
    SettlementRecoveryV1,
    BookingRecoveryV1,
    ShadowPnlV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownSink {
    Machine,
    Observation,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum EffectPolicy {
    MustPrecedeNewRisk,
    ObservationBoundedFailure,
    PreserveResult,
    ReconciliationFailClosed,
    RiskReducingContinues,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ConsumerDisposition {
    Relevant,
    Irrelevant,
}

pub(crate) fn resolve_identity(kind: &str, schema_version: u32) -> anyhow::Result<KnownIdentity> {
    match (kind, schema_version) {
        ("blocked_strategy_input_observation", 1) => {
            Ok(KnownIdentity::BlockedStrategyInputObservationV1)
        }
        ("strategy_input_snapshot", 16) => Ok(KnownIdentity::SubmitLinkedStrategyInputSnapshotV1),
        ("order_intent", 16) => Ok(KnownIdentity::EntryOrderIntentV1),
        ("risk_reducing_exit_order_intent", 1) => Ok(KnownIdentity::RiskReducingExitOrderIntentV1),
        ("admission_decision", 16) => Ok(KnownIdentity::AdmittedEntryAdmissionV1),
        ("rejected_entry_admission", 1) => Ok(KnownIdentity::RejectedEntryAdmissionV1),
        ("risk_reducing_exit_admission", 1) => Ok(KnownIdentity::RiskReducingExitAdmissionV1),
        ("forced_reduction_admission", 1) => Ok(KnownIdentity::ForcedReductionAdmissionV1),
        ("basket_admission_granted", 1) => Ok(KnownIdentity::BasketAdmissionGrantedV1),
        ("basket_admission_rejected", 1) => Ok(KnownIdentity::BasketAdmissionRejectedV1),
        ("capital_admission_rebuild", 16) => Ok(KnownIdentity::CapitalAdmissionRebuildV1),
        ("submit_reservation_metadata", 16) => Ok(KnownIdentity::SubmitReservationMetadataV1),
        ("submit_reservation_fill", 16) => Ok(KnownIdentity::SubmitReservationFillV1),
        ("entry_skip", 16) => Ok(KnownIdentity::EntrySkipObservationV1),
        ("exit_submission_decision", 1) => Ok(KnownIdentity::ExitSubmissionDecisionV1),
        ("exit_hold_decision", 1) => Ok(KnownIdentity::ExitHoldDecisionV1),
        ("exit_evaluation", 16) => Ok(KnownIdentity::ExitEvaluationV1),
        ("loss_governor_halt", 16) => Ok(KnownIdentity::LossGovernorHaltV1),
        ("order_reject", 16) => Ok(KnownIdentity::OrderRejectV1),
        ("order_lifecycle", 16) => Ok(KnownIdentity::OrderLifecycleV1),
        ("requote_throttle", 16) => Ok(KnownIdentity::RequoteThrottleObservationV1),
        ("settlement", 16) => Ok(KnownIdentity::SettlementV1),
        ("settlement_booking_error", 16) => Ok(KnownIdentity::SettlementBookingErrorV1),
        ("terminal_settlement", 16) => Ok(KnownIdentity::TerminalSettlementV1),
        ("venue_truth_capture_failure", 16) => Ok(KnownIdentity::VenueTruthCaptureFailureV1),
        ("venue_truth_divergence", 16) => Ok(KnownIdentity::VenueTruthDivergenceV1),
        _ => Err(anyhow::anyhow!(
            "unregistered decision-evidence identity (`{kind}`, {schema_version})"
        )),
    }
}

pub(crate) const fn current_identity_for_purpose(purpose: KnownPurpose) -> KnownIdentity {
    match purpose {
        KnownPurpose::BlockedStrategyInputObservation => {
            KnownIdentity::BlockedStrategyInputObservationV1
        }
        KnownPurpose::SubmitLinkedStrategyInputSnapshot => {
            KnownIdentity::SubmitLinkedStrategyInputSnapshotV1
        }
        KnownPurpose::EntryOrderIntent => KnownIdentity::EntryOrderIntentV1,
        KnownPurpose::RiskReducingExitOrderIntent => KnownIdentity::RiskReducingExitOrderIntentV1,
        KnownPurpose::AdmittedEntryAdmission => KnownIdentity::AdmittedEntryAdmissionV1,
        KnownPurpose::RejectedEntryAdmission => KnownIdentity::RejectedEntryAdmissionV1,
        KnownPurpose::RiskReducingExitAdmission => KnownIdentity::RiskReducingExitAdmissionV1,
        KnownPurpose::ForcedReductionAdmission => KnownIdentity::ForcedReductionAdmissionV1,
        KnownPurpose::BasketAdmissionGranted => KnownIdentity::BasketAdmissionGrantedV1,
        KnownPurpose::BasketAdmissionRejected => KnownIdentity::BasketAdmissionRejectedV1,
        KnownPurpose::CapitalAdmissionRebuild => KnownIdentity::CapitalAdmissionRebuildV1,
        KnownPurpose::SubmitReservationMetadata => KnownIdentity::SubmitReservationMetadataV1,
        KnownPurpose::SubmitReservationFill => KnownIdentity::SubmitReservationFillV1,
        KnownPurpose::EntrySkipObservation => KnownIdentity::EntrySkipObservationV1,
        KnownPurpose::ExitSubmissionDecision => KnownIdentity::ExitSubmissionDecisionV1,
        KnownPurpose::ExitHoldDecision => KnownIdentity::ExitHoldDecisionV1,
        KnownPurpose::ExitEvaluation => KnownIdentity::ExitEvaluationV1,
        KnownPurpose::LossGovernorHalt => KnownIdentity::LossGovernorHaltV1,
        KnownPurpose::OrderReject => KnownIdentity::OrderRejectV1,
        KnownPurpose::OrderLifecycle => KnownIdentity::OrderLifecycleV1,
        KnownPurpose::RequoteThrottleObservation => KnownIdentity::RequoteThrottleObservationV1,
        KnownPurpose::Settlement => KnownIdentity::SettlementV1,
        KnownPurpose::SettlementBookingError => KnownIdentity::SettlementBookingErrorV1,
        KnownPurpose::TerminalSettlement => KnownIdentity::TerminalSettlementV1,
        KnownPurpose::VenueTruthCaptureFailure => KnownIdentity::VenueTruthCaptureFailureV1,
        KnownPurpose::VenueTruthDivergence => KnownIdentity::VenueTruthDivergenceV1,
    }
}

pub(crate) const fn purpose_for_identity(identity: KnownIdentity) -> KnownPurpose {
    match identity {
        KnownIdentity::BlockedStrategyInputObservationV1 => {
            KnownPurpose::BlockedStrategyInputObservation
        }
        KnownIdentity::SubmitLinkedStrategyInputSnapshotV1 => {
            KnownPurpose::SubmitLinkedStrategyInputSnapshot
        }
        KnownIdentity::EntryOrderIntentV1 => KnownPurpose::EntryOrderIntent,
        KnownIdentity::RiskReducingExitOrderIntentV1 => KnownPurpose::RiskReducingExitOrderIntent,
        KnownIdentity::AdmittedEntryAdmissionV1 => KnownPurpose::AdmittedEntryAdmission,
        KnownIdentity::RejectedEntryAdmissionV1 => KnownPurpose::RejectedEntryAdmission,
        KnownIdentity::RiskReducingExitAdmissionV1 => KnownPurpose::RiskReducingExitAdmission,
        KnownIdentity::ForcedReductionAdmissionV1 => KnownPurpose::ForcedReductionAdmission,
        KnownIdentity::BasketAdmissionGrantedV1 => KnownPurpose::BasketAdmissionGranted,
        KnownIdentity::BasketAdmissionRejectedV1 => KnownPurpose::BasketAdmissionRejected,
        KnownIdentity::CapitalAdmissionRebuildV1 => KnownPurpose::CapitalAdmissionRebuild,
        KnownIdentity::SubmitReservationMetadataV1 => KnownPurpose::SubmitReservationMetadata,
        KnownIdentity::SubmitReservationFillV1 => KnownPurpose::SubmitReservationFill,
        KnownIdentity::EntrySkipObservationV1 => KnownPurpose::EntrySkipObservation,
        KnownIdentity::ExitSubmissionDecisionV1 => KnownPurpose::ExitSubmissionDecision,
        KnownIdentity::ExitHoldDecisionV1 => KnownPurpose::ExitHoldDecision,
        KnownIdentity::ExitEvaluationV1 => KnownPurpose::ExitEvaluation,
        KnownIdentity::LossGovernorHaltV1 => KnownPurpose::LossGovernorHalt,
        KnownIdentity::OrderRejectV1 => KnownPurpose::OrderReject,
        KnownIdentity::OrderLifecycleV1 => KnownPurpose::OrderLifecycle,
        KnownIdentity::RequoteThrottleObservationV1 => KnownPurpose::RequoteThrottleObservation,
        KnownIdentity::SettlementV1 => KnownPurpose::Settlement,
        KnownIdentity::SettlementBookingErrorV1 => KnownPurpose::SettlementBookingError,
        KnownIdentity::TerminalSettlementV1 => KnownPurpose::TerminalSettlement,
        KnownIdentity::VenueTruthCaptureFailureV1 => KnownPurpose::VenueTruthCaptureFailure,
        KnownIdentity::VenueTruthDivergenceV1 => KnownPurpose::VenueTruthDivergence,
    }
}

pub(crate) const fn sink_for_purpose(purpose: KnownPurpose) -> KnownSink {
    match purpose {
        KnownPurpose::BlockedStrategyInputObservation => KnownSink::Observation,
        KnownPurpose::SubmitLinkedStrategyInputSnapshot => KnownSink::Machine,
        KnownPurpose::EntryOrderIntent => KnownSink::Machine,
        KnownPurpose::RiskReducingExitOrderIntent => KnownSink::Machine,
        KnownPurpose::AdmittedEntryAdmission => KnownSink::Machine,
        KnownPurpose::RejectedEntryAdmission => KnownSink::Machine,
        KnownPurpose::RiskReducingExitAdmission => KnownSink::Machine,
        KnownPurpose::ForcedReductionAdmission => KnownSink::Machine,
        KnownPurpose::BasketAdmissionGranted => KnownSink::Machine,
        KnownPurpose::BasketAdmissionRejected => KnownSink::Machine,
        KnownPurpose::CapitalAdmissionRebuild => KnownSink::Machine,
        KnownPurpose::SubmitReservationMetadata => KnownSink::Machine,
        KnownPurpose::SubmitReservationFill => KnownSink::Machine,
        KnownPurpose::EntrySkipObservation => KnownSink::Observation,
        KnownPurpose::ExitSubmissionDecision => KnownSink::Machine,
        KnownPurpose::ExitHoldDecision => KnownSink::Observation,
        KnownPurpose::ExitEvaluation => KnownSink::Observation,
        KnownPurpose::LossGovernorHalt => KnownSink::Machine,
        KnownPurpose::OrderReject => KnownSink::Machine,
        KnownPurpose::OrderLifecycle => KnownSink::Machine,
        KnownPurpose::RequoteThrottleObservation => KnownSink::Observation,
        KnownPurpose::Settlement => KnownSink::Machine,
        KnownPurpose::SettlementBookingError => KnownSink::Machine,
        KnownPurpose::TerminalSettlement => KnownSink::Machine,
        KnownPurpose::VenueTruthCaptureFailure => KnownSink::Machine,
        KnownPurpose::VenueTruthDivergence => KnownSink::Machine,
    }
}

pub(crate) const fn sink_for_identity(identity: KnownIdentity) -> KnownSink {
    sink_for_purpose(purpose_for_identity(identity))
}

pub(crate) const fn effect_policy_for_purpose(purpose: KnownPurpose) -> EffectPolicy {
    match purpose {
        KnownPurpose::BlockedStrategyInputObservation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::SubmitLinkedStrategyInputSnapshot => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::EntryOrderIntent => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::RiskReducingExitOrderIntent => EffectPolicy::RiskReducingContinues,
        KnownPurpose::AdmittedEntryAdmission => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::RejectedEntryAdmission => EffectPolicy::PreserveResult,
        KnownPurpose::RiskReducingExitAdmission => EffectPolicy::RiskReducingContinues,
        KnownPurpose::ForcedReductionAdmission => EffectPolicy::RiskReducingContinues,
        KnownPurpose::BasketAdmissionGranted => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::BasketAdmissionRejected => EffectPolicy::PreserveResult,
        KnownPurpose::CapitalAdmissionRebuild => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::SubmitReservationMetadata => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::SubmitReservationFill => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::EntrySkipObservation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::ExitSubmissionDecision => EffectPolicy::RiskReducingContinues,
        KnownPurpose::ExitHoldDecision => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::ExitEvaluation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::LossGovernorHalt => EffectPolicy::PreserveResult,
        KnownPurpose::OrderReject => EffectPolicy::PreserveResult,
        KnownPurpose::OrderLifecycle => EffectPolicy::PreserveResult,
        KnownPurpose::RequoteThrottleObservation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::Settlement => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::SettlementBookingError => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::TerminalSettlement => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::VenueTruthCaptureFailure => EffectPolicy::RiskReducingContinues,
        KnownPurpose::VenueTruthDivergence => EffectPolicy::PreserveResult,
    }
}

pub(crate) const fn facts_for_identity(identity: KnownIdentity) -> &'static [KnownDecodedFact] {
    match identity {
        KnownIdentity::BlockedStrategyInputObservationV1 => {
            &[KnownDecodedFact::BlockedStrategyInputObservationV1]
        }
        KnownIdentity::SubmitLinkedStrategyInputSnapshotV1 => {
            &[KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1]
        }
        KnownIdentity::EntryOrderIntentV1 => &[KnownDecodedFact::EntryOrderIntentV1],
        KnownIdentity::RiskReducingExitOrderIntentV1 => {
            &[KnownDecodedFact::RiskReducingExitOrderIntentV1]
        }
        KnownIdentity::AdmittedEntryAdmissionV1 => &[KnownDecodedFact::AdmittedEntryAdmissionV1],
        KnownIdentity::RejectedEntryAdmissionV1 => &[KnownDecodedFact::RejectedEntryAdmissionV1],
        KnownIdentity::RiskReducingExitAdmissionV1 => {
            &[KnownDecodedFact::RiskReducingExitAdmissionV1]
        }
        KnownIdentity::ForcedReductionAdmissionV1 => {
            &[KnownDecodedFact::ForcedReductionAdmissionV1]
        }
        KnownIdentity::BasketAdmissionGrantedV1 => &[KnownDecodedFact::BasketAdmissionGrantedV1],
        KnownIdentity::BasketAdmissionRejectedV1 => &[KnownDecodedFact::BasketAdmissionRejectedV1],
        KnownIdentity::CapitalAdmissionRebuildV1 => &[KnownDecodedFact::CapitalAdmissionRebuildV1],
        KnownIdentity::SubmitReservationMetadataV1 => {
            &[KnownDecodedFact::SubmitReservationMetadataV1]
        }
        KnownIdentity::SubmitReservationFillV1 => &[KnownDecodedFact::SubmitReservationFillV1],
        KnownIdentity::EntrySkipObservationV1 => &[KnownDecodedFact::EntrySkipObservationV1],
        KnownIdentity::ExitSubmissionDecisionV1 => &[KnownDecodedFact::ExitSubmissionDecisionV1],
        KnownIdentity::ExitHoldDecisionV1 => &[KnownDecodedFact::ExitHoldDecisionV1],
        KnownIdentity::ExitEvaluationV1 => &[KnownDecodedFact::ExitEvaluationV1],
        KnownIdentity::LossGovernorHaltV1 => &[KnownDecodedFact::LossGovernorHaltV1],
        KnownIdentity::OrderRejectV1 => &[KnownDecodedFact::OrderRejectV1],
        KnownIdentity::OrderLifecycleV1 => &[KnownDecodedFact::OrderLifecycleV1],
        KnownIdentity::RequoteThrottleObservationV1 => {
            &[KnownDecodedFact::RequoteThrottleObservationV1]
        }
        KnownIdentity::SettlementV1 => &[KnownDecodedFact::SettlementV1],
        KnownIdentity::SettlementBookingErrorV1 => &[KnownDecodedFact::SettlementBookingErrorV1],
        KnownIdentity::TerminalSettlementV1 => &[KnownDecodedFact::TerminalSettlementV1],
        KnownIdentity::VenueTruthCaptureFailureV1 => {
            &[KnownDecodedFact::VenueTruthCaptureFailureV1]
        }
        KnownIdentity::VenueTruthDivergenceV1 => &[KnownDecodedFact::VenueTruthDivergenceV1],
    }
}

pub(crate) const fn identity_metadata(
    identity: KnownIdentity,
) -> (&'static str, u32, &'static str, &'static str) {
    match identity {
        KnownIdentity::BlockedStrategyInputObservationV1 => (
            "blocked_strategy_input_observation",
            1,
            "bolt_v3.strategy_input_snapshot",
            "blocked_strategy_input_observation",
        ),
        KnownIdentity::SubmitLinkedStrategyInputSnapshotV1 => (
            "strategy_input_snapshot",
            16,
            "bolt_v3.strategy_input_snapshot",
            "snapshot",
        ),
        KnownIdentity::EntryOrderIntentV1 => ("order_intent", 16, "bolt_v3.order_intent", "intent"),
        KnownIdentity::RiskReducingExitOrderIntentV1 => (
            "risk_reducing_exit_order_intent",
            1,
            "bolt_v3.order_intent",
            "intent",
        ),
        KnownIdentity::AdmittedEntryAdmissionV1 => (
            "admission_decision",
            16,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::RejectedEntryAdmissionV1 => (
            "rejected_entry_admission",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::RiskReducingExitAdmissionV1 => (
            "risk_reducing_exit_admission",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::ForcedReductionAdmissionV1 => (
            "forced_reduction_admission",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::BasketAdmissionGrantedV1 => (
            "basket_admission_granted",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::BasketAdmissionRejectedV1 => (
            "basket_admission_rejected",
            1,
            "bolt_v3.submit_admission",
            "decision",
        ),
        KnownIdentity::CapitalAdmissionRebuildV1 => (
            "capital_admission_rebuild",
            16,
            "bolt_v3.capital_admission_rebuild",
            "audit",
        ),
        KnownIdentity::SubmitReservationMetadataV1 => (
            "submit_reservation_metadata",
            16,
            "bolt_v3.submit_admission",
            "metadata",
        ),
        KnownIdentity::SubmitReservationFillV1 => (
            "submit_reservation_fill",
            16,
            "bolt_v3.submit_admission",
            "fill",
        ),
        KnownIdentity::EntrySkipObservationV1 => {
            ("entry_skip", 16, "bolt_v3.entry_skip", "entry_skip")
        }
        KnownIdentity::ExitSubmissionDecisionV1 => (
            "exit_submission_decision",
            1,
            "bolt_v3.exit_decision",
            "exit_decision",
        ),
        KnownIdentity::ExitHoldDecisionV1 => (
            "exit_hold_decision",
            1,
            "bolt_v3.exit_decision",
            "exit_decision",
        ),
        KnownIdentity::ExitEvaluationV1 => (
            "exit_evaluation",
            16,
            "bolt_v3.exit_evaluation",
            "exit_evaluation",
        ),
        KnownIdentity::LossGovernorHaltV1 => (
            "loss_governor_halt",
            16,
            "bolt_v3.loss_governor_halt",
            "loss_governor_halt",
        ),
        KnownIdentity::OrderRejectV1 => {
            ("order_reject", 16, "bolt_v3.order_reject", "order_reject")
        }
        KnownIdentity::OrderLifecycleV1 => (
            "order_lifecycle",
            16,
            "bolt_v3.order_lifecycle",
            "order_lifecycle",
        ),
        KnownIdentity::RequoteThrottleObservationV1 => (
            "requote_throttle",
            16,
            "bolt_v3.requote_throttle",
            "requote_throttle",
        ),
        KnownIdentity::SettlementV1 => ("settlement", 16, "bolt_v3.settlement", "settlement"),
        KnownIdentity::SettlementBookingErrorV1 => (
            "settlement_booking_error",
            16,
            "bolt_v3.settlement",
            "settlement_booking_error",
        ),
        KnownIdentity::TerminalSettlementV1 => (
            "terminal_settlement",
            16,
            "bolt_v3.settlement",
            "terminal_settlement",
        ),
        KnownIdentity::VenueTruthCaptureFailureV1 => (
            "venue_truth_capture_failure",
            16,
            "bolt_v3.venue_truth_capture_failure",
            "venue_truth_capture_failure",
        ),
        KnownIdentity::VenueTruthDivergenceV1 => (
            "venue_truth_divergence",
            16,
            "bolt_v3.venue_truth_divergence",
            "venue_truth_divergence",
        ),
    }
}

pub(crate) const fn disposition(
    fact: KnownDecodedFact,
    consumer: KnownConsumer,
) -> ConsumerDisposition {
    match (fact, consumer) {
        (
            KnownDecodedFact::BlockedStrategyInputObservationV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (
            KnownDecodedFact::BlockedStrategyInputObservationV1,
            KnownConsumer::SettlementRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::BlockedStrategyInputObservationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BlockedStrategyInputObservationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (
            KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1,
            KnownConsumer::SettlementRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (
            KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1,
            KnownConsumer::BookingRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::SubmitLinkedStrategyInputSnapshotV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Relevant
        }
        (KnownDecodedFact::EntryOrderIntentV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntryOrderIntentV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntryOrderIntentV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntryOrderIntentV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Relevant
        }
        (
            KnownDecodedFact::RiskReducingExitOrderIntentV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::RiskReducingExitOrderIntentV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RiskReducingExitOrderIntentV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RiskReducingExitOrderIntentV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::AdmittedEntryAdmissionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::AdmittedEntryAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::AdmittedEntryAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::AdmittedEntryAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Relevant
        }
        (
            KnownDecodedFact::RejectedEntryAdmissionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::RejectedEntryAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RejectedEntryAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RejectedEntryAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::RiskReducingExitAdmissionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::RiskReducingExitAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RiskReducingExitAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RiskReducingExitAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::ForcedReductionAdmissionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::ForcedReductionAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ForcedReductionAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ForcedReductionAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::BasketAdmissionGrantedV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::BasketAdmissionGrantedV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionGrantedV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionGrantedV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::BasketAdmissionRejectedV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::BasketAdmissionRejectedV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionRejectedV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::BasketAdmissionRejectedV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::CapitalAdmissionRebuildV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::CapitalAdmissionRebuildV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::CapitalAdmissionRebuildV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::CapitalAdmissionRebuildV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::SubmitReservationMetadataV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Relevant,
        (KnownDecodedFact::SubmitReservationMetadataV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationMetadataV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationMetadataV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationFillV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Relevant
        }
        (KnownDecodedFact::SubmitReservationFillV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationFillV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SubmitReservationFillV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntrySkipObservationV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntrySkipObservationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntrySkipObservationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::EntrySkipObservationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::ExitSubmissionDecisionV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::ExitSubmissionDecisionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitSubmissionDecisionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitSubmissionDecisionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitHoldDecisionV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitHoldDecisionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitHoldDecisionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitHoldDecisionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitEvaluationV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitEvaluationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitEvaluationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::ExitEvaluationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::LossGovernorHaltV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::LossGovernorHaltV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::LossGovernorHaltV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::LossGovernorHaltV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderRejectV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderRejectV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderRejectV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderRejectV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderLifecycleV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderLifecycleV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderLifecycleV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::OrderLifecycleV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::RequoteThrottleObservationV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::RequoteThrottleObservationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RequoteThrottleObservationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::RequoteThrottleObservationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Relevant
        }
        (KnownDecodedFact::SettlementV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::SettlementBookingErrorV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::SettlementBookingErrorV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::SettlementBookingErrorV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Relevant
        }
        (KnownDecodedFact::SettlementBookingErrorV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::TerminalSettlementV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::TerminalSettlementV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::TerminalSettlementV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Relevant
        }
        (KnownDecodedFact::TerminalSettlementV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (
            KnownDecodedFact::VenueTruthCaptureFailureV1,
            KnownConsumer::SubmitReservationRecoveryV1,
        ) => ConsumerDisposition::Irrelevant,
        (KnownDecodedFact::VenueTruthCaptureFailureV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthCaptureFailureV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthCaptureFailureV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthDivergenceV1, KnownConsumer::SubmitReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthDivergenceV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthDivergenceV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant
        }
        (KnownDecodedFact::VenueTruthDivergenceV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant
        }
    }
}
