// Generated by generate_decision_evidence_contract; do not edit.

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownProducer {
    EdgeTakerBlockedStrategyInput,
    EdgeTakerSubmitStrategyInput,
    OrderExecutionEntryIntent,
    OrderExecutionExitIntent,
    SubmitAdmissionAdmittedEntry,
    SubmitAdmissionRejectedEntry,
    SubmitAdmissionExit,
    SubmitAdmissionForcedReduction,
    BasketAdmissionGranted,
    BasketAdmissionRejected,
    CapitalAdmissionRebuild,
    SubmitReservationMetadata,
    SubmitReservationFill,
    EdgeTakerEntrySkip,
    EdgeTakerExitSubmitDecision,
    EdgeTakerExitHoldDecision,
    EdgeTakerExitEvaluation,
    SubmitAdmissionLossHalt,
    SubmitAdmissionOrderReject,
    OrderRejectObserverFeed,
    EdgeTakerOrderLifecycle,
    MakerRequoteThrottle,
    EdgeTakerSettlement,
    EdgeTakerTerminalSettlement,
    SubmitAdmissionVenueCaptureFailure,
    SubmitAdmissionVenueDivergence,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownPurpose {
    BlockedStrategyInputObservation,
    SubmitLinkedStrategyInputSnapshot,
    EntryOrderIntent,
    RiskReducingExitOrderIntent,
    AdmittedEntryAdmission,
    RejectedEntryAdmission,
    RiskReducingExitAdmission,
    ForcedReductionAdmission,
    BasketAdmissionGranted,
    BasketAdmissionRejected,
    CapitalAdmissionRebuild,
    SubmitReservationMetadata,
    SubmitReservationFill,
    EntrySkipObservation,
    ExitSubmissionDecision,
    ExitHoldDecision,
    ExitEvaluation,
    LossGovernorHalt,
    OrderReject,
    OrderLifecycle,
    RequoteThrottleObservation,
    Settlement,
    TerminalSettlement,
    VenueTruthCaptureFailure,
    VenueTruthDivergence,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownIdentity {
    BlockedStrategyInputObservationV1,
    SubmitLinkedStrategyInputSnapshotV1,
    EntryOrderIntentV1,
    RiskReducingExitOrderIntentV1,
    AdmittedEntryAdmissionV1,
    RejectedEntryAdmissionV1,
    RiskReducingExitAdmissionV1,
    ForcedReductionAdmissionV1,
    BasketAdmissionGrantedV1,
    BasketAdmissionRejectedV1,
    CapitalAdmissionRebuildV1,
    SubmitReservationMetadataV1,
    SubmitReservationFillV1,
    EntrySkipObservationV1,
    ExitSubmissionDecisionV1,
    ExitHoldDecisionV1,
    ExitEvaluationV1,
    LossGovernorHaltV1,
    OrderRejectV1,
    OrderLifecycleV1,
    RequoteThrottleObservationV1,
    SettlementV1,
    TerminalSettlementV1,
    VenueTruthCaptureFailureV1,
    VenueTruthDivergenceV1,
}

#[cfg(test)]
pub(crate) const ALL_IDENTITIES: &[KnownIdentity] = &[
    KnownIdentity::BlockedStrategyInputObservationV1,
    KnownIdentity::SubmitLinkedStrategyInputSnapshotV1,
    KnownIdentity::EntryOrderIntentV1,
    KnownIdentity::RiskReducingExitOrderIntentV1,
    KnownIdentity::AdmittedEntryAdmissionV1,
    KnownIdentity::RejectedEntryAdmissionV1,
    KnownIdentity::RiskReducingExitAdmissionV1,
    KnownIdentity::ForcedReductionAdmissionV1,
    KnownIdentity::BasketAdmissionGrantedV1,
    KnownIdentity::BasketAdmissionRejectedV1,
    KnownIdentity::CapitalAdmissionRebuildV1,
    KnownIdentity::SubmitReservationMetadataV1,
    KnownIdentity::SubmitReservationFillV1,
    KnownIdentity::EntrySkipObservationV1,
    KnownIdentity::ExitSubmissionDecisionV1,
    KnownIdentity::ExitHoldDecisionV1,
    KnownIdentity::ExitEvaluationV1,
    KnownIdentity::LossGovernorHaltV1,
    KnownIdentity::OrderRejectV1,
    KnownIdentity::OrderLifecycleV1,
    KnownIdentity::RequoteThrottleObservationV1,
    KnownIdentity::SettlementV1,
    KnownIdentity::TerminalSettlementV1,
    KnownIdentity::VenueTruthCaptureFailureV1,
    KnownIdentity::VenueTruthDivergenceV1,
];

pub(crate) mod identities {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct BlockedStrategyInputObservationV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct SubmitLinkedStrategyInputSnapshotV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct EntryOrderIntentV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct RiskReducingExitOrderIntentV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct AdmittedEntryAdmissionV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct RejectedEntryAdmissionV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct RiskReducingExitAdmissionV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct ForcedReductionAdmissionV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct BasketAdmissionGrantedV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct BasketAdmissionRejectedV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct CapitalAdmissionRebuildV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct SubmitReservationMetadataV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct SubmitReservationFillV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct EntrySkipObservationV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct ExitSubmissionDecisionV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct ExitHoldDecisionV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct ExitEvaluationV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct LossGovernorHaltV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct OrderRejectV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct OrderLifecycleV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct RequoteThrottleObservationV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct SettlementV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct TerminalSettlementV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct VenueTruthCaptureFailureV1;
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub(crate) struct VenueTruthDivergenceV1;
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownFact {
    BlockedStrategyInputObservationV1,
    SubmitLinkedStrategyInputSnapshotV1,
    EntryOrderIntentV1,
    RiskReducingExitOrderIntentV1,
    AdmittedEntryAdmissionV1,
    RejectedEntryAdmissionV1,
    RiskReducingExitAdmissionV1,
    ForcedReductionAdmissionV1,
    BasketAdmissionGrantedV1,
    BasketAdmissionRejectedV1,
    CapitalAdmissionRebuildV1,
    SubmitReservationMetadataV1,
    SubmitReservationFillV1,
    EntrySkipObservationV1,
    ExitSubmissionDecisionV1,
    ExitHoldDecisionV1,
    ExitEvaluationV1,
    LossGovernorHaltV1,
    OrderRejectV1,
    OrderLifecycleV1,
    RequoteThrottleObservationV1,
    SettlementV1,
    TerminalSettlementV1,
    VenueTruthCaptureFailureV1,
    VenueTruthDivergenceV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownConsumer {
    ReservationRecoveryV1,
    SettlementRecoveryV1,
    BookingRecoveryV1,
    ShadowPnlV1,
    BacktestRunGuardV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum KnownSink {
    Machine,
    Observation,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum EffectPolicy {
    MustPrecedeNewRisk,
    ObservationBoundedFailure,
    PreserveResult,
    ReconciliationFailClosed,
    RiskReducingContinues,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct IdentityDescriptor {
    pub(crate) kind: &'static str,
    pub(crate) schema_version: u32,
    pub(crate) gate_id: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ConsumerDisposition {
    Relevant(KnownFact),
    Irrelevant(&'static str),
}

pub(crate) const fn current_identity_for_purpose(purpose: KnownPurpose) -> KnownIdentity {
    match purpose {
        KnownPurpose::BlockedStrategyInputObservation => {
            KnownIdentity::BlockedStrategyInputObservationV1
        }
        KnownPurpose::SubmitLinkedStrategyInputSnapshot => {
            KnownIdentity::SubmitLinkedStrategyInputSnapshotV1
        }
        KnownPurpose::EntryOrderIntent => KnownIdentity::EntryOrderIntentV1,
        KnownPurpose::RiskReducingExitOrderIntent => KnownIdentity::RiskReducingExitOrderIntentV1,
        KnownPurpose::AdmittedEntryAdmission => KnownIdentity::AdmittedEntryAdmissionV1,
        KnownPurpose::RejectedEntryAdmission => KnownIdentity::RejectedEntryAdmissionV1,
        KnownPurpose::RiskReducingExitAdmission => KnownIdentity::RiskReducingExitAdmissionV1,
        KnownPurpose::ForcedReductionAdmission => KnownIdentity::ForcedReductionAdmissionV1,
        KnownPurpose::BasketAdmissionGranted => KnownIdentity::BasketAdmissionGrantedV1,
        KnownPurpose::BasketAdmissionRejected => KnownIdentity::BasketAdmissionRejectedV1,
        KnownPurpose::CapitalAdmissionRebuild => KnownIdentity::CapitalAdmissionRebuildV1,
        KnownPurpose::SubmitReservationMetadata => KnownIdentity::SubmitReservationMetadataV1,
        KnownPurpose::SubmitReservationFill => KnownIdentity::SubmitReservationFillV1,
        KnownPurpose::EntrySkipObservation => KnownIdentity::EntrySkipObservationV1,
        KnownPurpose::ExitSubmissionDecision => KnownIdentity::ExitSubmissionDecisionV1,
        KnownPurpose::ExitHoldDecision => KnownIdentity::ExitHoldDecisionV1,
        KnownPurpose::ExitEvaluation => KnownIdentity::ExitEvaluationV1,
        KnownPurpose::LossGovernorHalt => KnownIdentity::LossGovernorHaltV1,
        KnownPurpose::OrderReject => KnownIdentity::OrderRejectV1,
        KnownPurpose::OrderLifecycle => KnownIdentity::OrderLifecycleV1,
        KnownPurpose::RequoteThrottleObservation => KnownIdentity::RequoteThrottleObservationV1,
        KnownPurpose::Settlement => KnownIdentity::SettlementV1,
        KnownPurpose::TerminalSettlement => KnownIdentity::TerminalSettlementV1,
        KnownPurpose::VenueTruthCaptureFailure => KnownIdentity::VenueTruthCaptureFailureV1,
        KnownPurpose::VenueTruthDivergence => KnownIdentity::VenueTruthDivergenceV1,
    }
}

pub(crate) const fn sink_for_purpose(purpose: KnownPurpose) -> KnownSink {
    match purpose {
        KnownPurpose::BlockedStrategyInputObservation => KnownSink::Observation,
        KnownPurpose::SubmitLinkedStrategyInputSnapshot => KnownSink::Machine,
        KnownPurpose::EntryOrderIntent => KnownSink::Machine,
        KnownPurpose::RiskReducingExitOrderIntent => KnownSink::Machine,
        KnownPurpose::AdmittedEntryAdmission => KnownSink::Machine,
        KnownPurpose::RejectedEntryAdmission => KnownSink::Machine,
        KnownPurpose::RiskReducingExitAdmission => KnownSink::Machine,
        KnownPurpose::ForcedReductionAdmission => KnownSink::Machine,
        KnownPurpose::BasketAdmissionGranted => KnownSink::Machine,
        KnownPurpose::BasketAdmissionRejected => KnownSink::Machine,
        KnownPurpose::CapitalAdmissionRebuild => KnownSink::Machine,
        KnownPurpose::SubmitReservationMetadata => KnownSink::Machine,
        KnownPurpose::SubmitReservationFill => KnownSink::Machine,
        KnownPurpose::EntrySkipObservation => KnownSink::Observation,
        KnownPurpose::ExitSubmissionDecision => KnownSink::Machine,
        KnownPurpose::ExitHoldDecision => KnownSink::Observation,
        KnownPurpose::ExitEvaluation => KnownSink::Observation,
        KnownPurpose::LossGovernorHalt => KnownSink::Machine,
        KnownPurpose::OrderReject => KnownSink::Machine,
        KnownPurpose::OrderLifecycle => KnownSink::Machine,
        KnownPurpose::RequoteThrottleObservation => KnownSink::Observation,
        KnownPurpose::Settlement => KnownSink::Machine,
        KnownPurpose::TerminalSettlement => KnownSink::Machine,
        KnownPurpose::VenueTruthCaptureFailure => KnownSink::Machine,
        KnownPurpose::VenueTruthDivergence => KnownSink::Machine,
    }
}

pub(crate) const fn effect_policy_for_purpose(purpose: KnownPurpose) -> EffectPolicy {
    match purpose {
        KnownPurpose::BlockedStrategyInputObservation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::SubmitLinkedStrategyInputSnapshot => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::EntryOrderIntent => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::RiskReducingExitOrderIntent => EffectPolicy::RiskReducingContinues,
        KnownPurpose::AdmittedEntryAdmission => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::RejectedEntryAdmission => EffectPolicy::PreserveResult,
        KnownPurpose::RiskReducingExitAdmission => EffectPolicy::RiskReducingContinues,
        KnownPurpose::ForcedReductionAdmission => EffectPolicy::RiskReducingContinues,
        KnownPurpose::BasketAdmissionGranted => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::BasketAdmissionRejected => EffectPolicy::PreserveResult,
        KnownPurpose::CapitalAdmissionRebuild => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::SubmitReservationMetadata => EffectPolicy::MustPrecedeNewRisk,
        KnownPurpose::SubmitReservationFill => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::EntrySkipObservation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::ExitSubmissionDecision => EffectPolicy::RiskReducingContinues,
        KnownPurpose::ExitHoldDecision => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::ExitEvaluation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::LossGovernorHalt => EffectPolicy::PreserveResult,
        KnownPurpose::OrderReject => EffectPolicy::PreserveResult,
        KnownPurpose::OrderLifecycle => EffectPolicy::PreserveResult,
        KnownPurpose::RequoteThrottleObservation => EffectPolicy::ObservationBoundedFailure,
        KnownPurpose::Settlement => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::TerminalSettlement => EffectPolicy::ReconciliationFailClosed,
        KnownPurpose::VenueTruthCaptureFailure => EffectPolicy::RiskReducingContinues,
        KnownPurpose::VenueTruthDivergence => EffectPolicy::PreserveResult,
    }
}

pub(crate) const fn purpose_for_producer(producer: KnownProducer) -> KnownPurpose {
    match producer {
        KnownProducer::EdgeTakerBlockedStrategyInput => {
            KnownPurpose::BlockedStrategyInputObservation
        }
        KnownProducer::EdgeTakerSubmitStrategyInput => {
            KnownPurpose::SubmitLinkedStrategyInputSnapshot
        }
        KnownProducer::OrderExecutionEntryIntent => KnownPurpose::EntryOrderIntent,
        KnownProducer::OrderExecutionExitIntent => KnownPurpose::RiskReducingExitOrderIntent,
        KnownProducer::SubmitAdmissionAdmittedEntry => KnownPurpose::AdmittedEntryAdmission,
        KnownProducer::SubmitAdmissionRejectedEntry => KnownPurpose::RejectedEntryAdmission,
        KnownProducer::SubmitAdmissionExit => KnownPurpose::RiskReducingExitAdmission,
        KnownProducer::SubmitAdmissionForcedReduction => KnownPurpose::ForcedReductionAdmission,
        KnownProducer::BasketAdmissionGranted => KnownPurpose::BasketAdmissionGranted,
        KnownProducer::BasketAdmissionRejected => KnownPurpose::BasketAdmissionRejected,
        KnownProducer::CapitalAdmissionRebuild => KnownPurpose::CapitalAdmissionRebuild,
        KnownProducer::SubmitReservationMetadata => KnownPurpose::SubmitReservationMetadata,
        KnownProducer::SubmitReservationFill => KnownPurpose::SubmitReservationFill,
        KnownProducer::EdgeTakerEntrySkip => KnownPurpose::EntrySkipObservation,
        KnownProducer::EdgeTakerExitSubmitDecision => KnownPurpose::ExitSubmissionDecision,
        KnownProducer::EdgeTakerExitHoldDecision => KnownPurpose::ExitHoldDecision,
        KnownProducer::EdgeTakerExitEvaluation => KnownPurpose::ExitEvaluation,
        KnownProducer::SubmitAdmissionLossHalt => KnownPurpose::LossGovernorHalt,
        KnownProducer::SubmitAdmissionOrderReject => KnownPurpose::OrderReject,
        KnownProducer::OrderRejectObserverFeed => KnownPurpose::OrderReject,
        KnownProducer::EdgeTakerOrderLifecycle => KnownPurpose::OrderLifecycle,
        KnownProducer::MakerRequoteThrottle => KnownPurpose::RequoteThrottleObservation,
        KnownProducer::EdgeTakerSettlement => KnownPurpose::Settlement,
        KnownProducer::EdgeTakerTerminalSettlement => KnownPurpose::TerminalSettlement,
        KnownProducer::SubmitAdmissionVenueCaptureFailure => KnownPurpose::VenueTruthCaptureFailure,
        KnownProducer::SubmitAdmissionVenueDivergence => KnownPurpose::VenueTruthDivergence,
    }
}

pub(crate) const fn purpose_for_identity(identity: KnownIdentity) -> KnownPurpose {
    match identity {
        KnownIdentity::BlockedStrategyInputObservationV1 => {
            KnownPurpose::BlockedStrategyInputObservation
        }
        KnownIdentity::SubmitLinkedStrategyInputSnapshotV1 => {
            KnownPurpose::SubmitLinkedStrategyInputSnapshot
        }
        KnownIdentity::EntryOrderIntentV1 => KnownPurpose::EntryOrderIntent,
        KnownIdentity::RiskReducingExitOrderIntentV1 => KnownPurpose::RiskReducingExitOrderIntent,
        KnownIdentity::AdmittedEntryAdmissionV1 => KnownPurpose::AdmittedEntryAdmission,
        KnownIdentity::RejectedEntryAdmissionV1 => KnownPurpose::RejectedEntryAdmission,
        KnownIdentity::RiskReducingExitAdmissionV1 => KnownPurpose::RiskReducingExitAdmission,
        KnownIdentity::ForcedReductionAdmissionV1 => KnownPurpose::ForcedReductionAdmission,
        KnownIdentity::BasketAdmissionGrantedV1 => KnownPurpose::BasketAdmissionGranted,
        KnownIdentity::BasketAdmissionRejectedV1 => KnownPurpose::BasketAdmissionRejected,
        KnownIdentity::CapitalAdmissionRebuildV1 => KnownPurpose::CapitalAdmissionRebuild,
        KnownIdentity::SubmitReservationMetadataV1 => KnownPurpose::SubmitReservationMetadata,
        KnownIdentity::SubmitReservationFillV1 => KnownPurpose::SubmitReservationFill,
        KnownIdentity::EntrySkipObservationV1 => KnownPurpose::EntrySkipObservation,
        KnownIdentity::ExitSubmissionDecisionV1 => KnownPurpose::ExitSubmissionDecision,
        KnownIdentity::ExitHoldDecisionV1 => KnownPurpose::ExitHoldDecision,
        KnownIdentity::ExitEvaluationV1 => KnownPurpose::ExitEvaluation,
        KnownIdentity::LossGovernorHaltV1 => KnownPurpose::LossGovernorHalt,
        KnownIdentity::OrderRejectV1 => KnownPurpose::OrderReject,
        KnownIdentity::OrderLifecycleV1 => KnownPurpose::OrderLifecycle,
        KnownIdentity::RequoteThrottleObservationV1 => KnownPurpose::RequoteThrottleObservation,
        KnownIdentity::SettlementV1 => KnownPurpose::Settlement,
        KnownIdentity::TerminalSettlementV1 => KnownPurpose::TerminalSettlement,
        KnownIdentity::VenueTruthCaptureFailureV1 => KnownPurpose::VenueTruthCaptureFailure,
        KnownIdentity::VenueTruthDivergenceV1 => KnownPurpose::VenueTruthDivergence,
    }
}

pub(crate) const fn fact_for_identity(identity: KnownIdentity) -> KnownFact {
    match identity {
        KnownIdentity::BlockedStrategyInputObservationV1 => {
            KnownFact::BlockedStrategyInputObservationV1
        }
        KnownIdentity::SubmitLinkedStrategyInputSnapshotV1 => {
            KnownFact::SubmitLinkedStrategyInputSnapshotV1
        }
        KnownIdentity::EntryOrderIntentV1 => KnownFact::EntryOrderIntentV1,
        KnownIdentity::RiskReducingExitOrderIntentV1 => KnownFact::RiskReducingExitOrderIntentV1,
        KnownIdentity::AdmittedEntryAdmissionV1 => KnownFact::AdmittedEntryAdmissionV1,
        KnownIdentity::RejectedEntryAdmissionV1 => KnownFact::RejectedEntryAdmissionV1,
        KnownIdentity::RiskReducingExitAdmissionV1 => KnownFact::RiskReducingExitAdmissionV1,
        KnownIdentity::ForcedReductionAdmissionV1 => KnownFact::ForcedReductionAdmissionV1,
        KnownIdentity::BasketAdmissionGrantedV1 => KnownFact::BasketAdmissionGrantedV1,
        KnownIdentity::BasketAdmissionRejectedV1 => KnownFact::BasketAdmissionRejectedV1,
        KnownIdentity::CapitalAdmissionRebuildV1 => KnownFact::CapitalAdmissionRebuildV1,
        KnownIdentity::SubmitReservationMetadataV1 => KnownFact::SubmitReservationMetadataV1,
        KnownIdentity::SubmitReservationFillV1 => KnownFact::SubmitReservationFillV1,
        KnownIdentity::EntrySkipObservationV1 => KnownFact::EntrySkipObservationV1,
        KnownIdentity::ExitSubmissionDecisionV1 => KnownFact::ExitSubmissionDecisionV1,
        KnownIdentity::ExitHoldDecisionV1 => KnownFact::ExitHoldDecisionV1,
        KnownIdentity::ExitEvaluationV1 => KnownFact::ExitEvaluationV1,
        KnownIdentity::LossGovernorHaltV1 => KnownFact::LossGovernorHaltV1,
        KnownIdentity::OrderRejectV1 => KnownFact::OrderRejectV1,
        KnownIdentity::OrderLifecycleV1 => KnownFact::OrderLifecycleV1,
        KnownIdentity::RequoteThrottleObservationV1 => KnownFact::RequoteThrottleObservationV1,
        KnownIdentity::SettlementV1 => KnownFact::SettlementV1,
        KnownIdentity::TerminalSettlementV1 => KnownFact::TerminalSettlementV1,
        KnownIdentity::VenueTruthCaptureFailureV1 => KnownFact::VenueTruthCaptureFailureV1,
        KnownIdentity::VenueTruthDivergenceV1 => KnownFact::VenueTruthDivergenceV1,
    }
}

pub(crate) const fn descriptor_for_identity(identity: KnownIdentity) -> IdentityDescriptor {
    match identity {
        KnownIdentity::BlockedStrategyInputObservationV1 => IdentityDescriptor {
            kind: "blocked_strategy_input_observation",
            schema_version: 1,
            gate_id: "bolt_v3.strategy_input_snapshot",
        },
        KnownIdentity::SubmitLinkedStrategyInputSnapshotV1 => IdentityDescriptor {
            kind: "strategy_input_snapshot",
            schema_version: 16,
            gate_id: "bolt_v3.strategy_input_snapshot",
        },
        KnownIdentity::EntryOrderIntentV1 => IdentityDescriptor {
            kind: "order_intent",
            schema_version: 16,
            gate_id: "bolt_v3.order_intent",
        },
        KnownIdentity::RiskReducingExitOrderIntentV1 => IdentityDescriptor {
            kind: "risk_reducing_exit_order_intent",
            schema_version: 1,
            gate_id: "bolt_v3.order_intent",
        },
        KnownIdentity::AdmittedEntryAdmissionV1 => IdentityDescriptor {
            kind: "admission_decision",
            schema_version: 16,
            gate_id: "bolt_v3.submit_admission",
        },
        KnownIdentity::RejectedEntryAdmissionV1 => IdentityDescriptor {
            kind: "rejected_entry_admission",
            schema_version: 1,
            gate_id: "bolt_v3.submit_admission",
        },
        KnownIdentity::RiskReducingExitAdmissionV1 => IdentityDescriptor {
            kind: "risk_reducing_exit_admission",
            schema_version: 1,
            gate_id: "bolt_v3.submit_admission",
        },
        KnownIdentity::ForcedReductionAdmissionV1 => IdentityDescriptor {
            kind: "forced_reduction_admission",
            schema_version: 1,
            gate_id: "bolt_v3.submit_admission",
        },
        KnownIdentity::BasketAdmissionGrantedV1 => IdentityDescriptor {
            kind: "basket_admission_granted",
            schema_version: 1,
            gate_id: "bolt_v3.submit_admission",
        },
        KnownIdentity::BasketAdmissionRejectedV1 => IdentityDescriptor {
            kind: "basket_admission_rejected",
            schema_version: 1,
            gate_id: "bolt_v3.submit_admission",
        },
        KnownIdentity::CapitalAdmissionRebuildV1 => IdentityDescriptor {
            kind: "capital_admission_rebuild",
            schema_version: 16,
            gate_id: "bolt_v3.capital_admission_rebuild",
        },
        KnownIdentity::SubmitReservationMetadataV1 => IdentityDescriptor {
            kind: "submit_reservation_metadata",
            schema_version: 16,
            gate_id: "bolt_v3.submit_admission",
        },
        KnownIdentity::SubmitReservationFillV1 => IdentityDescriptor {
            kind: "submit_reservation_fill",
            schema_version: 16,
            gate_id: "bolt_v3.submit_admission",
        },
        KnownIdentity::EntrySkipObservationV1 => IdentityDescriptor {
            kind: "entry_skip",
            schema_version: 16,
            gate_id: "bolt_v3.entry_skip",
        },
        KnownIdentity::ExitSubmissionDecisionV1 => IdentityDescriptor {
            kind: "exit_submission_decision",
            schema_version: 1,
            gate_id: "bolt_v3.exit_decision",
        },
        KnownIdentity::ExitHoldDecisionV1 => IdentityDescriptor {
            kind: "exit_hold_decision",
            schema_version: 1,
            gate_id: "bolt_v3.exit_decision",
        },
        KnownIdentity::ExitEvaluationV1 => IdentityDescriptor {
            kind: "exit_evaluation",
            schema_version: 16,
            gate_id: "bolt_v3.exit_evaluation",
        },
        KnownIdentity::LossGovernorHaltV1 => IdentityDescriptor {
            kind: "loss_governor_halt",
            schema_version: 16,
            gate_id: "bolt_v3.loss_governor_halt",
        },
        KnownIdentity::OrderRejectV1 => IdentityDescriptor {
            kind: "order_reject",
            schema_version: 16,
            gate_id: "bolt_v3.order_reject",
        },
        KnownIdentity::OrderLifecycleV1 => IdentityDescriptor {
            kind: "order_lifecycle",
            schema_version: 16,
            gate_id: "bolt_v3.order_lifecycle",
        },
        KnownIdentity::RequoteThrottleObservationV1 => IdentityDescriptor {
            kind: "requote_throttle",
            schema_version: 16,
            gate_id: "bolt_v3.requote_throttle",
        },
        KnownIdentity::SettlementV1 => IdentityDescriptor {
            kind: "settlement",
            schema_version: 16,
            gate_id: "bolt_v3.settlement",
        },
        KnownIdentity::TerminalSettlementV1 => IdentityDescriptor {
            kind: "terminal_settlement",
            schema_version: 16,
            gate_id: "bolt_v3.settlement",
        },
        KnownIdentity::VenueTruthCaptureFailureV1 => IdentityDescriptor {
            kind: "venue_truth_capture_failure",
            schema_version: 16,
            gate_id: "bolt_v3.capital_admission_rebuild",
        },
        KnownIdentity::VenueTruthDivergenceV1 => IdentityDescriptor {
            kind: "venue_truth_divergence",
            schema_version: 16,
            gate_id: "bolt_v3.capital_admission_rebuild",
        },
    }
}

pub(crate) const fn disposition_for(
    fact: KnownFact,
    consumer: KnownConsumer,
) -> ConsumerDisposition {
    match (fact, consumer) {
        (KnownFact::BlockedStrategyInputObservationV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BlockedStrategyInputObservationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BlockedStrategyInputObservationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BlockedStrategyInputObservationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitLinkedStrategyInputSnapshotV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitLinkedStrategyInputSnapshotV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitLinkedStrategyInputSnapshotV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitLinkedStrategyInputSnapshotV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Relevant(KnownFact::SubmitLinkedStrategyInputSnapshotV1)
        }
        (KnownFact::EntryOrderIntentV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::EntryOrderIntentV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::EntryOrderIntentV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::EntryOrderIntentV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Relevant(KnownFact::EntryOrderIntentV1)
        }
        (KnownFact::RiskReducingExitOrderIntentV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RiskReducingExitOrderIntentV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RiskReducingExitOrderIntentV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RiskReducingExitOrderIntentV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::AdmittedEntryAdmissionV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::AdmittedEntryAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::AdmittedEntryAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::AdmittedEntryAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Relevant(KnownFact::AdmittedEntryAdmissionV1)
        }
        (KnownFact::RejectedEntryAdmissionV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RejectedEntryAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RejectedEntryAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RejectedEntryAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RiskReducingExitAdmissionV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RiskReducingExitAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RiskReducingExitAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RiskReducingExitAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ForcedReductionAdmissionV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ForcedReductionAdmissionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ForcedReductionAdmissionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ForcedReductionAdmissionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BasketAdmissionGrantedV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BasketAdmissionGrantedV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BasketAdmissionGrantedV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BasketAdmissionGrantedV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BasketAdmissionRejectedV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BasketAdmissionRejectedV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BasketAdmissionRejectedV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BasketAdmissionRejectedV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::CapitalAdmissionRebuildV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::CapitalAdmissionRebuildV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::CapitalAdmissionRebuildV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::CapitalAdmissionRebuildV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitReservationMetadataV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Relevant(KnownFact::SubmitReservationMetadataV1)
        }
        (KnownFact::SubmitReservationMetadataV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitReservationMetadataV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitReservationMetadataV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitReservationFillV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Relevant(KnownFact::SubmitReservationFillV1)
        }
        (KnownFact::SubmitReservationFillV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitReservationFillV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SubmitReservationFillV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::EntrySkipObservationV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::EntrySkipObservationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::EntrySkipObservationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::EntrySkipObservationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitSubmissionDecisionV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitSubmissionDecisionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitSubmissionDecisionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitSubmissionDecisionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitHoldDecisionV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitHoldDecisionV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitHoldDecisionV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitHoldDecisionV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitEvaluationV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitEvaluationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitEvaluationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::ExitEvaluationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::LossGovernorHaltV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::LossGovernorHaltV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::LossGovernorHaltV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::LossGovernorHaltV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::OrderRejectV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::OrderRejectV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::OrderRejectV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::OrderRejectV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::OrderLifecycleV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::OrderLifecycleV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::OrderLifecycleV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::OrderLifecycleV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RequoteThrottleObservationV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RequoteThrottleObservationV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RequoteThrottleObservationV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::RequoteThrottleObservationV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SettlementV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SettlementV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Relevant(KnownFact::SettlementV1)
        }
        (KnownFact::SettlementV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::SettlementV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::TerminalSettlementV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::TerminalSettlementV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Relevant(KnownFact::TerminalSettlementV1)
        }
        (KnownFact::TerminalSettlementV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Relevant(KnownFact::TerminalSettlementV1)
        }
        (KnownFact::TerminalSettlementV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::VenueTruthCaptureFailureV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::VenueTruthCaptureFailureV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::VenueTruthCaptureFailureV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::VenueTruthCaptureFailureV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::VenueTruthDivergenceV1, KnownConsumer::ReservationRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::VenueTruthDivergenceV1, KnownConsumer::SettlementRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::VenueTruthDivergenceV1, KnownConsumer::BookingRecoveryV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::VenueTruthDivergenceV1, KnownConsumer::ShadowPnlV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_22")
        }
        (KnownFact::BlockedStrategyInputObservationV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::BlockedStrategyInputObservationV1)
        }
        (KnownFact::SubmitLinkedStrategyInputSnapshotV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::SubmitLinkedStrategyInputSnapshotV1)
        }
        (KnownFact::EntryOrderIntentV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::EntryOrderIntentV1)
        }
        (KnownFact::RiskReducingExitOrderIntentV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::AdmittedEntryAdmissionV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::AdmittedEntryAdmissionV1)
        }
        (KnownFact::RejectedEntryAdmissionV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::RejectedEntryAdmissionV1)
        }
        (KnownFact::RiskReducingExitAdmissionV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::RiskReducingExitAdmissionV1)
        }
        (KnownFact::ForcedReductionAdmissionV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::ForcedReductionAdmissionV1)
        }
        (KnownFact::BasketAdmissionGrantedV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::BasketAdmissionRejectedV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::CapitalAdmissionRebuildV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::SubmitReservationMetadataV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::SubmitReservationMetadataV1)
        }
        (KnownFact::SubmitReservationFillV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::SubmitReservationFillV1)
        }
        (KnownFact::EntrySkipObservationV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::EntrySkipObservationV1)
        }
        (KnownFact::ExitSubmissionDecisionV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::ExitSubmissionDecisionV1)
        }
        (KnownFact::ExitHoldDecisionV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::ExitHoldDecisionV1)
        }
        (KnownFact::ExitEvaluationV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::LossGovernorHaltV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::LossGovernorHaltV1)
        }
        (KnownFact::OrderRejectV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::OrderLifecycleV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::RequoteThrottleObservationV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Relevant(KnownFact::RequoteThrottleObservationV1)
        }
        (KnownFact::SettlementV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::TerminalSettlementV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::VenueTruthCaptureFailureV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
        (KnownFact::VenueTruthDivergenceV1, KnownConsumer::BacktestRunGuardV1) => {
            ConsumerDisposition::Irrelevant("current_contract_owner_ruling_2026_07_23_backtest")
        }
    }
}

pub(crate) fn resolve_identity(kind: &str, schema_version: u32) -> Option<KnownIdentity> {
    if kind == "blocked_strategy_input_observation" && schema_version == 1 {
        return Some(KnownIdentity::BlockedStrategyInputObservationV1);
    }
    if kind == "strategy_input_snapshot" && schema_version == 16 {
        return Some(KnownIdentity::SubmitLinkedStrategyInputSnapshotV1);
    }
    if kind == "order_intent" && schema_version == 16 {
        return Some(KnownIdentity::EntryOrderIntentV1);
    }
    if kind == "risk_reducing_exit_order_intent" && schema_version == 1 {
        return Some(KnownIdentity::RiskReducingExitOrderIntentV1);
    }
    if kind == "admission_decision" && schema_version == 16 {
        return Some(KnownIdentity::AdmittedEntryAdmissionV1);
    }
    if kind == "rejected_entry_admission" && schema_version == 1 {
        return Some(KnownIdentity::RejectedEntryAdmissionV1);
    }
    if kind == "risk_reducing_exit_admission" && schema_version == 1 {
        return Some(KnownIdentity::RiskReducingExitAdmissionV1);
    }
    if kind == "forced_reduction_admission" && schema_version == 1 {
        return Some(KnownIdentity::ForcedReductionAdmissionV1);
    }
    if kind == "basket_admission_granted" && schema_version == 1 {
        return Some(KnownIdentity::BasketAdmissionGrantedV1);
    }
    if kind == "basket_admission_rejected" && schema_version == 1 {
        return Some(KnownIdentity::BasketAdmissionRejectedV1);
    }
    if kind == "capital_admission_rebuild" && schema_version == 16 {
        return Some(KnownIdentity::CapitalAdmissionRebuildV1);
    }
    if kind == "submit_reservation_metadata" && schema_version == 16 {
        return Some(KnownIdentity::SubmitReservationMetadataV1);
    }
    if kind == "submit_reservation_fill" && schema_version == 16 {
        return Some(KnownIdentity::SubmitReservationFillV1);
    }
    if kind == "entry_skip" && schema_version == 16 {
        return Some(KnownIdentity::EntrySkipObservationV1);
    }
    if kind == "exit_submission_decision" && schema_version == 1 {
        return Some(KnownIdentity::ExitSubmissionDecisionV1);
    }
    if kind == "exit_hold_decision" && schema_version == 1 {
        return Some(KnownIdentity::ExitHoldDecisionV1);
    }
    if kind == "exit_evaluation" && schema_version == 16 {
        return Some(KnownIdentity::ExitEvaluationV1);
    }
    if kind == "loss_governor_halt" && schema_version == 16 {
        return Some(KnownIdentity::LossGovernorHaltV1);
    }
    if kind == "order_reject" && schema_version == 16 {
        return Some(KnownIdentity::OrderRejectV1);
    }
    if kind == "order_lifecycle" && schema_version == 16 {
        return Some(KnownIdentity::OrderLifecycleV1);
    }
    if kind == "requote_throttle" && schema_version == 16 {
        return Some(KnownIdentity::RequoteThrottleObservationV1);
    }
    if kind == "settlement" && schema_version == 16 {
        return Some(KnownIdentity::SettlementV1);
    }
    if kind == "terminal_settlement" && schema_version == 16 {
        return Some(KnownIdentity::TerminalSettlementV1);
    }
    if kind == "venue_truth_capture_failure" && schema_version == 16 {
        return Some(KnownIdentity::VenueTruthCaptureFailureV1);
    }
    if kind == "venue_truth_divergence" && schema_version == 16 {
        return Some(KnownIdentity::VenueTruthDivergenceV1);
    }
    None
}
