// @generated by scripts/generate_polymarket_redemption_config.py from polymarket-redemption.toml and polymarket-redemption-source-evidence.toml.
// Do not edit this file directly.

use alloy_primitives::U256;

use super::{RedemptionPreparationConfig, RedemptionProtocolFacts};

pub(super) const POLYMARKET_REDEMPTION_PREPARATION_CONFIG: RedemptionPreparationConfig =
    RedemptionPreparationConfig {
        schema_version: 1,
        production_activation_enabled: false,
        chain_id: 137,
        wallet_type: "SAFE",
        safe_address: alloy_primitives::address!("0xa3a5e9c062331237e5f1403b2bba7a184e5de983"),
        collateral_asset: alloy_primitives::address!("0xc011a7e12a19f7b1f670d46f03b03f3342e82dfb"),
        output_asset: alloy_primitives::address!("0xc011a7e12a19f7b1f670d46f03b03f3342e82dfb"),
        standard_adapter_target: alloy_primitives::address!(
            "0xada100874d00e3331d00f2007a9c336a65009718"
        ),
        negative_risk_adapter_target: alloy_primitives::address!(
            "0xada200001000ef00d07553cee7006808f895c6f1"
        ),
        parent_collection_id: alloy_primitives::b256!(
            "0x0000000000000000000000000000000000000000000000000000000000000000"
        ),
        dummy_index_sets: [
            U256::from_limbs([1, 0, 0, 0]),
            U256::from_limbs([2, 0, 0, 0]),
        ],
        maximum_safe_nonce_decimal_digits: 78,
        aws_region: "eu-west-2",
        signer_private_key_ssm_path: "/bolt/polymarket/private-key",
        builder_api_key_ssm_path: "/bolt/polymarket/builder/api-key",
        builder_api_secret_ssm_path: "/bolt/polymarket/builder/api-secret",
        builder_passphrase_ssm_path: "/bolt/polymarket/builder/passphrase",
    };

pub(super) const POLYMARKET_REDEMPTION_PROTOCOL: RedemptionProtocolFacts =
    RedemptionProtocolFacts {
        function_selector: [1, 183, 3, 124],
        operation: 0,
        value: U256::from_limbs([0, 0, 0, 0]),
        safe_tx_gas: U256::from_limbs([0, 0, 0, 0]),
        base_gas: U256::from_limbs([0, 0, 0, 0]),
        gas_price: U256::from_limbs([0, 0, 0, 0]),
        gas_token: alloy_primitives::address!("0x0000000000000000000000000000000000000000"),
        refund_receiver: alloy_primitives::address!("0x0000000000000000000000000000000000000000"),
        metadata: "",
    };
