// @generated by scripts/generate_polymarket_redemption_config.py from polymarket-redemption.toml, polymarket-redemption-source-evidence.toml, and root.toml.
// Do not edit this file directly.

use alloy_primitives::U256;

use super::{RedemptionPreparationConfig, RedemptionProtocolFacts};

pub(super) const POLYMARKET_REDEMPTION_PREPARATION_CONFIG: RedemptionPreparationConfig =
    RedemptionPreparationConfig {
        schema_version: 1,
        production_activation_enabled: false,
        chain_id: 137,
        wallet_type: "SAFE",
        safe_address: alloy_primitives::address!("0xa3a5e9c062331237e5f1403b2bba7a184e5de983"),
        collateral_asset: alloy_primitives::address!("0xc011a7e12a19f7b1f670d46f03b03f3342e82dfb"),
        standard_adapter_target: alloy_primitives::address!(
            "0xada100db00ca00073811820692005400218fce1f"
        ),
        negative_risk_adapter_target: alloy_primitives::address!(
            "0xada2005600dec949baf300f4c6120000bdb6eaab"
        ),
        parent_collection_id: alloy_primitives::b256!(
            "0x0000000000000000000000000000000000000000000000000000000000000000"
        ),
        dummy_index_sets: [
            U256::from_limbs([1, 0, 0, 0]),
            U256::from_limbs([2, 0, 0, 0]),
        ],
        maximum_safe_nonce_decimal_digits: 78,
    };

pub(super) const POLYMARKET_REDEMPTION_PROTOCOL: RedemptionProtocolFacts =
    RedemptionProtocolFacts {
        function_selector: [1, 183, 3, 124],
        operation: 0,
        value: U256::from_limbs([0, 0, 0, 0]),
        safe_tx_gas: U256::from_limbs([0, 0, 0, 0]),
        base_gas: U256::from_limbs([0, 0, 0, 0]),
        gas_price: U256::from_limbs([0, 0, 0, 0]),
        gas_token: alloy_primitives::address!("0x0000000000000000000000000000000000000000"),
        refund_receiver: alloy_primitives::address!("0x0000000000000000000000000000000000000000"),
        metadata: "",
    };
