// @generated by the Rust evidence-novelty generator from
// config/evidence-novelty.toml. Do not edit.

use crate::bolt_v3_decision_evidence::{BoltV3BinaryOutcomeEdgeBlockReason, BoltV3EntryBlockReason, BoltV3EntryPricingBlockReason, BoltV3EntrySkipReasonCategory, BoltV3ExposureOccupancy, BoltV3ForcedFlatReason, BoltV3OutcomeSide, BoltV3RvGateResult};
use crate::bolt_v3_market_families::MarketSelectionOutcome;
use crate::bolt_v3_realized_volatility::{RealizedVolBlockReason, RealizedVolSourceRejectReason, RealizedVolSourceStatus};
use super::{CanonicalSet, CanonicalSourceStates, NoveltyEligibleProducer, private};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EvidenceProducerOwner {
    EntrySkip,
    BlockedStrategyInputSnapshot,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EvidenceAvailability {
    Unavailable,
    Available,
}

impl From<bool> for EvidenceAvailability {
    fn from(value: bool) -> Self {
        match value {
            false => Self::Unavailable,
            true => Self::Available,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EvidenceCoherence {
    Coherent,
    Incoherent,
}

impl From<bool> for EvidenceCoherence {
    fn from(value: bool) -> Self {
        match value {
            false => Self::Coherent,
            true => Self::Incoherent,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EvidenceWatermark {
    Absent,
    Present,
}

impl From<bool> for EvidenceWatermark {
    fn from(value: bool) -> Self {
        match value {
            false => Self::Absent,
            true => Self::Present,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EvidenceFailover {
    Unavailable,
    Primary,
    FailedOver,
}

impl From<Option<bool>> for EvidenceFailover {
    fn from(value: Option<bool>) -> Self {
        match value {
            None => Self::Unavailable,
            Some(false) => Self::Primary,
            Some(true) => Self::FailedOver,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EvidenceEnablement {
    Disabled,
    Enabled,
}

impl From<bool> for EvidenceEnablement {
    fn from(value: bool) -> Self {
        match value {
            false => Self::Disabled,
            true => Self::Enabled,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EvidenceQuorumParticipation {
    DiagnosticOnly,
    CountsTowardQuorum,
}

impl From<bool> for EvidenceQuorumParticipation {
    fn from(value: bool) -> Self {
        match value {
            false => Self::DiagnosticOnly,
            true => Self::CountsTowardQuorum,
        }
    }
}

pub(super) fn validate_entry_skip_reason(value: &BoltV3EntrySkipReasonCategory) -> anyhow::Result<()> {
    match value {
        BoltV3EntrySkipReasonCategory::StrategyCoreNotRegistered => Ok(()),
        BoltV3EntrySkipReasonCategory::EntryGateBlocked => Ok(()),
        BoltV3EntrySkipReasonCategory::EntryPricingBlocked => Ok(()),
        BoltV3EntrySkipReasonCategory::NoSideSelected => Ok(()),
        BoltV3EntrySkipReasonCategory::SizedNotionalNotPositive => Ok(()),
        BoltV3EntrySkipReasonCategory::InstrumentIdMissing => Ok(()),
        BoltV3EntrySkipReasonCategory::InstrumentMissingFromCache => Ok(()),
        BoltV3EntrySkipReasonCategory::EntryPriceMissing => Ok(()),
        BoltV3EntrySkipReasonCategory::QuantityRoundingFailed => Ok(()),
        BoltV3EntrySkipReasonCategory::LimitNotionalExceedsSizedNotional => Ok(()),
        BoltV3EntrySkipReasonCategory::EntryQuoteNotionalBelowVenueMinimum => Ok(()),
        BoltV3EntrySkipReasonCategory::EntryQuoteNotionalMinimumUnmodeled => Ok(()),
        BoltV3EntrySkipReasonCategory::QuantityNotPositive => Ok(()),
        BoltV3EntrySkipReasonCategory::PositionContractInvalid => Ok(()),
        BoltV3EntrySkipReasonCategory::EntryPositionContractUnsupported => Ok(()),
        BoltV3EntrySkipReasonCategory::HistoricalEntryFeeUnavailable => Ok(()),
        BoltV3EntrySkipReasonCategory::OnePositionInvariantViolation => Ok(()),
        BoltV3EntrySkipReasonCategory::EntryMalformedRejected => Ok(()),
        BoltV3EntrySkipReasonCategory::EntryBalanceRejected => Ok(()),
        BoltV3EntrySkipReasonCategory::EntryUnfillableRejectedUnchangedBook => Ok(()),
        BoltV3EntrySkipReasonCategory::Unclassified => anyhow::bail!("unregistered entry_skip_reason state Unclassified"),
    }
}

pub(super) fn validate_entry_gate_blocker(value: &BoltV3EntryBlockReason) -> anyhow::Result<()> {
    match value {
        BoltV3EntryBlockReason::PhaseNotActive => Ok(()),
        BoltV3EntryBlockReason::MetadataMismatch => Ok(()),
        BoltV3EntryBlockReason::ActiveBookNotPriced => Ok(()),
        BoltV3EntryBlockReason::BookCrossed => Ok(()),
        BoltV3EntryBlockReason::IntervalOpenMissing => Ok(()),
        BoltV3EntryBlockReason::WarmupIncomplete => Ok(()),
        BoltV3EntryBlockReason::FeesNotReady => Ok(()),
        BoltV3EntryBlockReason::RecoveryMode => Ok(()),
        BoltV3EntryBlockReason::MarketCoolingDown => Ok(()),
        BoltV3EntryBlockReason::SpotSpikeCooldown => Ok(()),
        BoltV3EntryBlockReason::ForcedFlat(value_0) => {
            validate_forced_flat_reason(value_0)?;
            Ok(())
        }
        BoltV3EntryBlockReason::OnePositionInvariant(value_0) => {
            validate_exposure_occupancy(value_0)?;
            Ok(())
        }
    }
}

pub(super) fn validate_forced_flat_reason(value: &BoltV3ForcedFlatReason) -> anyhow::Result<()> {
    match value {
        BoltV3ForcedFlatReason::Freeze => Ok(()),
        BoltV3ForcedFlatReason::StaleReference => Ok(()),
        BoltV3ForcedFlatReason::ThinBook => Ok(()),
        BoltV3ForcedFlatReason::MetadataMismatch => Ok(()),
        BoltV3ForcedFlatReason::FastVenueIncoherent => Ok(()),
    }
}

pub(super) fn validate_exposure_occupancy(value: &BoltV3ExposureOccupancy) -> anyhow::Result<()> {
    match value {
        BoltV3ExposureOccupancy::PendingEntry => Ok(()),
        BoltV3ExposureOccupancy::EntryReconcilePending => Ok(()),
        BoltV3ExposureOccupancy::ManagedPosition => Ok(()),
        BoltV3ExposureOccupancy::ExitPending => Ok(()),
        BoltV3ExposureOccupancy::UnsupportedObserved => Ok(()),
        BoltV3ExposureOccupancy::BlindRecovery => Ok(()),
    }
}

pub(super) fn validate_entry_pricing_blocker(value: &BoltV3EntryPricingBlockReason) -> anyhow::Result<()> {
    match value {
        BoltV3EntryPricingBlockReason::SpotPriceMissing => Ok(()),
        BoltV3EntryPricingBlockReason::ReferenceCurrentPriceStale => Ok(()),
        BoltV3EntryPricingBlockReason::StrikePriceMissing => Ok(()),
        BoltV3EntryPricingBlockReason::SecondsToExpiryMissing => Ok(()),
        BoltV3EntryPricingBlockReason::RealizedVolNotReady => Ok(()),
        BoltV3EntryPricingBlockReason::ThetaScalerUnavailable => Ok(()),
        BoltV3EntryPricingBlockReason::UncertaintyBandUnavailable => Ok(()),
        BoltV3EntryPricingBlockReason::FairProbabilityUnavailable => Ok(()),
        BoltV3EntryPricingBlockReason::FeeUnavailable(value_0) => {
            validate_outcome_side(value_0)?;
            Ok(())
        }
        BoltV3EntryPricingBlockReason::ExecutableEntryCostUnavailable(value_0) => {
            validate_outcome_side(value_0)?;
            Ok(())
        }
        BoltV3EntryPricingBlockReason::ExecutableEdgeUnavailable(value_0, value_1) => {
            validate_outcome_side(value_0)?;
            validate_binary_edge_blocker(value_1)?;
            Ok(())
        }
        BoltV3EntryPricingBlockReason::SizedNotionalUnsupported(value_0) => {
            validate_outcome_side(value_0)?;
            Ok(())
        }
    }
}

pub(super) fn validate_outcome_side(value: &BoltV3OutcomeSide) -> anyhow::Result<()> {
    match value {
        BoltV3OutcomeSide::Up => Ok(()),
        BoltV3OutcomeSide::Down => Ok(()),
    }
}

pub(super) fn validate_binary_edge_blocker(value: &BoltV3BinaryOutcomeEdgeBlockReason) -> anyhow::Result<()> {
    match value {
        BoltV3BinaryOutcomeEdgeBlockReason::MissingOrderBook => Ok(()),
        BoltV3BinaryOutcomeEdgeBlockReason::InsufficientDepth => Ok(()),
        BoltV3BinaryOutcomeEdgeBlockReason::InvalidProbability => Ok(()),
        BoltV3BinaryOutcomeEdgeBlockReason::InvalidCost => Ok(()),
        BoltV3BinaryOutcomeEdgeBlockReason::UnsupportedOrderShape => Ok(()),
        BoltV3BinaryOutcomeEdgeBlockReason::EdgeBelowThreshold => Ok(()),
        BoltV3BinaryOutcomeEdgeBlockReason::SpreadOrSlippageWipedEdge => Ok(()),
        BoltV3BinaryOutcomeEdgeBlockReason::FeeUnavailable => Ok(()),
    }
}

pub(super) fn validate_rv_gate_result(value: &BoltV3RvGateResult) -> anyhow::Result<()> {
    match value {
        BoltV3RvGateResult::Accepted => Ok(()),
        BoltV3RvGateResult::MissingSnapshot => Ok(()),
        BoltV3RvGateResult::MissingEvaluationEventTime => Ok(()),
        BoltV3RvGateResult::RejectedFutureDated => Ok(()),
        BoltV3RvGateResult::RejectedStale => Ok(()),
        BoltV3RvGateResult::RejectedNotReady => Ok(()),
    }
}

pub(super) fn validate_rv_blocker(value: &RealizedVolBlockReason) -> anyhow::Result<()> {
    match value {
        RealizedVolBlockReason::InvalidConfig => Ok(()),
        RealizedVolBlockReason::QuorumNotReady => Ok(()),
        RealizedVolBlockReason::SourceStale => Ok(()),
        RealizedVolBlockReason::CoverageBelowMinimum => Ok(()),
        RealizedVolBlockReason::InterSampleGapExceeded => Ok(()),
        RealizedVolBlockReason::SourceClassMismatch => Ok(()),
        RealizedVolBlockReason::SampleKindMismatch => Ok(()),
        RealizedVolBlockReason::CrossSourceDispersion => Ok(()),
        RealizedVolBlockReason::AnnualizationBasisInvalid => Ok(()),
        RealizedVolBlockReason::NotWarm => Ok(()),
    }
}

pub(super) fn validate_rv_source_status(value: &RealizedVolSourceStatus) -> anyhow::Result<()> {
    match value {
        RealizedVolSourceStatus::Ready => Ok(()),
        RealizedVolSourceStatus::Blocked => Ok(()),
        RealizedVolSourceStatus::DiagnosticOnly => Ok(()),
        RealizedVolSourceStatus::Waiting => Ok(()),
    }
}

pub(super) fn validate_rv_source_rejection(value: &RealizedVolSourceRejectReason) -> anyhow::Result<()> {
    match value {
        RealizedVolSourceRejectReason::DisabledSource => Ok(()),
        RealizedVolSourceRejectReason::InvalidPrice => Ok(()),
        RealizedVolSourceRejectReason::SourceClassMismatch => Ok(()),
        RealizedVolSourceRejectReason::SampleKindMismatch => Ok(()),
        RealizedVolSourceRejectReason::EventTimeRegression => Ok(()),
        RealizedVolSourceRejectReason::DuplicateTimestamp => Ok(()),
        RealizedVolSourceRejectReason::StaleSameEventUpdate => Ok(()),
        RealizedVolSourceRejectReason::ReceiveBeforeEvent => Ok(()),
        RealizedVolSourceRejectReason::EventReceiveLagExceeded => Ok(()),
    }
}

pub(super) fn validate_market_selection_outcome(value: &MarketSelectionOutcome) -> anyhow::Result<()> {
    match value {
        MarketSelectionOutcome::Current => Ok(()),
        MarketSelectionOutcome::Next => Ok(()),
    }
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct EntrySkipSemanticKey {
    reason: BoltV3EntrySkipReasonCategory,
    gate_blockers: CanonicalSet<BoltV3EntryBlockReason>,
    pricing_blockers: CanonicalSet<BoltV3EntryPricingBlockReason>,
    fast_venue: EvidenceAvailability,
    reference_current_price: EvidenceAvailability,
    fast_venue_coherence: EvidenceCoherence,
    rv_gate: BoltV3RvGateResult,
    rv_watermark: EvidenceWatermark,
}

impl EntrySkipSemanticKey {
    #[allow(clippy::too_many_arguments)]
    pub fn try_new(
        reason: BoltV3EntrySkipReasonCategory,
        gate_blockers: CanonicalSet<BoltV3EntryBlockReason>,
        pricing_blockers: CanonicalSet<BoltV3EntryPricingBlockReason>,
        fast_venue: EvidenceAvailability,
        reference_current_price: EvidenceAvailability,
        fast_venue_coherence: EvidenceCoherence,
        rv_gate: BoltV3RvGateResult,
        rv_watermark: EvidenceWatermark,
    ) -> anyhow::Result<Self> {
        validate_entry_skip_reason(&reason)?;
        for value in gate_blockers.iter() {
            validate_entry_gate_blocker(value)?;
        }
        for value in pricing_blockers.iter() {
            validate_entry_pricing_blocker(value)?;
        }
        validate_rv_gate_result(&rv_gate)?;
        Ok(Self {
            reason,
            gate_blockers,
            pricing_blockers,
            fast_venue,
            reference_current_price,
            fast_venue_coherence,
            rv_gate,
            rv_watermark,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EntrySkipProducer;
impl private::Sealed for EntrySkipProducer {}
impl NoveltyEligibleProducer for EntrySkipProducer {
    type Key = EntrySkipSemanticKey;
    const OWNER: EvidenceProducerOwner = EvidenceProducerOwner::EntrySkip;
    const PRODUCER_KIND: &'static str = "entry_skip";
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct BlockedStrategyInputSemanticKey {
    market_selection_outcome: MarketSelectionOutcome,
    gate_blockers: CanonicalSet<BoltV3EntryBlockReason>,
    pricing_blockers: CanonicalSet<BoltV3EntryPricingBlockReason>,
    selected_side: Option<BoltV3OutcomeSide>,
    fast_venue: EvidenceAvailability,
    reference_current_price: EvidenceAvailability,
    reference_failover: EvidenceFailover,
    fast_venue_coherence: EvidenceCoherence,
    rv_gate: BoltV3RvGateResult,
    rv_watermark: EvidenceWatermark,
    rv_blockers: CanonicalSet<RealizedVolBlockReason>,
    rv_source_states: CanonicalSourceStates,
}

impl BlockedStrategyInputSemanticKey {
    #[allow(clippy::too_many_arguments)]
    pub fn try_new(
        market_selection_outcome: MarketSelectionOutcome,
        gate_blockers: CanonicalSet<BoltV3EntryBlockReason>,
        pricing_blockers: CanonicalSet<BoltV3EntryPricingBlockReason>,
        selected_side: Option<BoltV3OutcomeSide>,
        fast_venue: EvidenceAvailability,
        reference_current_price: EvidenceAvailability,
        reference_failover: EvidenceFailover,
        fast_venue_coherence: EvidenceCoherence,
        rv_gate: BoltV3RvGateResult,
        rv_watermark: EvidenceWatermark,
        rv_blockers: CanonicalSet<RealizedVolBlockReason>,
        rv_source_states: CanonicalSourceStates,
    ) -> anyhow::Result<Self> {
        validate_market_selection_outcome(&market_selection_outcome)?;
        for value in gate_blockers.iter() {
            validate_entry_gate_blocker(value)?;
        }
        for value in pricing_blockers.iter() {
            validate_entry_pricing_blocker(value)?;
        }
        if let Some(value) = &selected_side {
            validate_outcome_side(value)?;
        }
        validate_rv_gate_result(&rv_gate)?;
        for value in rv_blockers.iter() {
            validate_rv_blocker(value)?;
        }
        Ok(Self {
            market_selection_outcome,
            gate_blockers,
            pricing_blockers,
            selected_side,
            fast_venue,
            reference_current_price,
            reference_failover,
            fast_venue_coherence,
            rv_gate,
            rv_watermark,
            rv_blockers,
            rv_source_states,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BlockedStrategyInputSnapshotProducer;
impl private::Sealed for BlockedStrategyInputSnapshotProducer {}
impl NoveltyEligibleProducer for BlockedStrategyInputSnapshotProducer {
    type Key = BlockedStrategyInputSemanticKey;
    const OWNER: EvidenceProducerOwner = EvidenceProducerOwner::BlockedStrategyInputSnapshot;
    const PRODUCER_KIND: &'static str = "strategy_input_snapshot";
}

pub const ENTRY_SKIP_PER_EPISODE_STATE_UPPER_BOUND: u128 = 4323455642275676160;

pub const BLOCKED_STRATEGY_INPUT_SNAPSHOT_STATIC_STATE_UPPER_BOUND: u128 = 3984496719921263149056;
pub const BLOCKED_STRATEGY_INPUT_SNAPSHOT_PER_REGISTERED_SOURCE_STATE_UPPER_BOUND: u128 = 1760;
pub fn blocked_strategy_input_snapshot_per_episode_state_upper_bound(registered_source_count: u32) -> Option<u128> {
    BLOCKED_STRATEGY_INPUT_SNAPSHOT_PER_REGISTERED_SOURCE_STATE_UPPER_BOUND.checked_pow(registered_source_count).and_then(|source_states| BLOCKED_STRATEGY_INPUT_SNAPSHOT_STATIC_STATE_UPPER_BOUND.checked_mul(source_states))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EvidenceDimensionRegistration {
    pub producer: &'static str,
    pub owner: EvidenceProducerOwner,
    pub name: &'static str,
    pub domain: &'static str,
    pub id: usize,
}

pub const EVIDENCE_NOVELTY_FAMILY_CAPACITY: usize = 256;
pub const EVIDENCE_DIMENSION_REGISTRATIONS: &[EvidenceDimensionRegistration] = &[
    EvidenceDimensionRegistration {
        producer: "entry_skip",
        owner: EvidenceProducerOwner::EntrySkip,
        name: "reason",
        domain: "entry_skip_reason",
        id: 144,
    },
    EvidenceDimensionRegistration {
        producer: "entry_skip",
        owner: EvidenceProducerOwner::EntrySkip,
        name: "gate_blockers",
        domain: "entry_gate_blocker",
        id: 145,
    },
    EvidenceDimensionRegistration {
        producer: "entry_skip",
        owner: EvidenceProducerOwner::EntrySkip,
        name: "pricing_blockers",
        domain: "entry_pricing_blocker",
        id: 146,
    },
    EvidenceDimensionRegistration {
        producer: "entry_skip",
        owner: EvidenceProducerOwner::EntrySkip,
        name: "fast_venue",
        domain: "availability",
        id: 147,
    },
    EvidenceDimensionRegistration {
        producer: "entry_skip",
        owner: EvidenceProducerOwner::EntrySkip,
        name: "reference_current_price",
        domain: "availability",
        id: 148,
    },
    EvidenceDimensionRegistration {
        producer: "entry_skip",
        owner: EvidenceProducerOwner::EntrySkip,
        name: "fast_venue_coherence",
        domain: "coherence",
        id: 149,
    },
    EvidenceDimensionRegistration {
        producer: "entry_skip",
        owner: EvidenceProducerOwner::EntrySkip,
        name: "rv_gate",
        domain: "rv_gate_result",
        id: 150,
    },
    EvidenceDimensionRegistration {
        producer: "entry_skip",
        owner: EvidenceProducerOwner::EntrySkip,
        name: "rv_watermark",
        domain: "watermark",
        id: 151,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "market_selection_outcome",
        domain: "market_selection_outcome",
        id: 152,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "gate_blockers",
        domain: "entry_gate_blocker",
        id: 153,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "pricing_blockers",
        domain: "entry_pricing_blocker",
        id: 154,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "selected_side",
        domain: "outcome_side",
        id: 155,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "fast_venue",
        domain: "availability",
        id: 156,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "reference_current_price",
        domain: "availability",
        id: 157,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "reference_failover",
        domain: "failover",
        id: 158,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "fast_venue_coherence",
        domain: "coherence",
        id: 159,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "rv_gate",
        domain: "rv_gate_result",
        id: 160,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "rv_watermark",
        domain: "watermark",
        id: 161,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "rv_blockers",
        domain: "rv_blocker",
        id: 162,
    },
    EvidenceDimensionRegistration {
        producer: "blocked_strategy_input_snapshot",
        owner: EvidenceProducerOwner::BlockedStrategyInputSnapshot,
        name: "rv_source_states",
        domain: "rv_source_status",
        id: 163,
    },
];

pub fn evidence_dimension_registration_by_id(id: usize) -> Option<&'static EvidenceDimensionRegistration> {
    EVIDENCE_DIMENSION_REGISTRATIONS.iter().find(|registration| registration.id == id)
}
