#!/usr/bin/env python3
"""Generate the Rust risk-closure workspace configuration from TOML."""

from __future__ import annotations

import argparse
import dataclasses
import pathlib
import sys
import tomllib


class ConfigError(ValueError):
    """The workspace source cannot produce a closed configuration."""


@dataclasses.dataclass(frozen=True)
class WorkspaceConfig:
    arena_bytes: int
    slot_bytes: int
    capacity: int
    production_activation_enabled: bool


def _exact_keys(table: dict[str, object], expected: set[str], context: str) -> None:
    unknown = sorted(set(table) - expected)
    missing = sorted(expected - set(table))
    if unknown:
        raise ConfigError(f"{context}: unknown field(s): {', '.join(unknown)}")
    if missing:
        raise ConfigError(f"{context}: missing field(s): {', '.join(missing)}")


def _positive_integer(value: object, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ConfigError(f"{field} must be a positive integer")
    return value


def load_config(path: pathlib.Path) -> WorkspaceConfig:
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError) as error:
        raise ConfigError(f"cannot read {path}: {error}") from error
    _exact_keys(
        document,
        {"schema_version", "production_activation_enabled", "risk_closure_workspaces"},
        "root",
    )
    schema_version = document["schema_version"]
    if (
        not isinstance(schema_version, int)
        or isinstance(schema_version, bool)
        or schema_version != 1
    ):
        raise ConfigError("schema_version must equal integer 1")
    activation = document["production_activation_enabled"]
    if activation is not False:
        raise ConfigError("production_activation_enabled must remain false")
    workspace = document["risk_closure_workspaces"]
    if not isinstance(workspace, dict):
        raise ConfigError("risk_closure_workspaces must be a table")
    _exact_keys(workspace, {"arena_bytes", "slot_bytes"}, "risk_closure_workspaces")
    arena_bytes = _positive_integer(workspace["arena_bytes"], "arena_bytes")
    slot_bytes = _positive_integer(workspace["slot_bytes"], "slot_bytes")
    if arena_bytes % slot_bytes != 0:
        raise ConfigError("risk_closure_workspaces.slot_bytes must evenly divide arena_bytes")
    capacity = arena_bytes // slot_bytes
    if capacity == 0:
        raise ConfigError("risk_closure_workspaces capacity must be positive")
    return WorkspaceConfig(
        arena_bytes=arena_bytes,
        slot_bytes=slot_bytes,
        capacity=capacity,
        production_activation_enabled=activation,
    )


def render_rust(config: WorkspaceConfig, source_name: str) -> str:
    activation = str(config.production_activation_enabled).lower()
    return f"""// @generated by scripts/generate_risk_closure_workspace_config.py from {source_name}.
// Do not edit this file directly.

const RISK_CLOSURE_WORKSPACE_CONFIG: super::RiskClosureWorkspaceConfig =
    super::RiskClosureWorkspaceConfig {{
        arena_bytes: {config.arena_bytes},
        slot_bytes: {config.slot_bytes},
        capacity: {config.capacity},
        production_activation_enabled: {activation},
    }};

#[cfg(test)]
pub(super) fn config() -> super::RiskClosureWorkspaceConfig {{
    RISK_CLOSURE_WORKSPACE_CONFIG
}}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    try:
        rendered = render_rust(load_config(arguments.source), arguments.source.name)
        if arguments.check:
            current = arguments.output.read_text(encoding="utf-8")
            if current != rendered:
                raise ConfigError(f"{arguments.output} is stale; regenerate it")
        else:
            arguments.output.write_text(rendered, encoding="utf-8")
    except (ConfigError, OSError, UnicodeDecodeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
