#!/usr/bin/env python3
"""Verify and deterministically generate the #1354 evidence novelty registry."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import tomllib
from dataclasses import dataclass


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
REGISTRY_PATH = pathlib.Path("config/evidence-novelty.toml")
GENERATED_PATH = pathlib.Path("src/bolt_v3_evidence_novelty_generated.rs")
NOVELTY_PATH = pathlib.Path("src/bolt_v3_evidence_novelty.rs")
PRODUCER_PATH = pathlib.Path("src/strategies/binary_oracle_edge_taker/mod.rs")


@dataclass(frozen=True)
class StateRow:
    rust_variant: str
    producer_kind: str
    semantic_state: str
    id_start: int
    id_end_exclusive: int

    @property
    def capacity(self) -> int:
        return self.id_end_exclusive - self.id_start


@dataclass(frozen=True)
class Registry:
    family_name: str
    family_capacity: int
    states: tuple[StateRow, ...]


def load_registry(path: pathlib.Path) -> Registry:
    document = tomllib.loads(path.read_text(encoding="utf-8"))
    if set(document) != {"schema_version", "family", "state"}:
        raise ValueError("registry must contain exactly schema_version, family, and state")
    if document["schema_version"] != 1:
        raise ValueError("registry schema_version must be 1")
    family = document["family"]
    if not isinstance(family, dict) or set(family) != {"name", "capacity"}:
        raise ValueError("family must contain exactly name and capacity")
    family_name = family["name"]
    family_capacity = family["capacity"]
    if not isinstance(family_name, str) or not re.fullmatch(r"[a-z][a-z0-9_]*", family_name):
        raise ValueError("family.name must be snake_case")
    if not isinstance(family_capacity, int) or family_capacity <= 0:
        raise ValueError("family.capacity must be a positive integer")

    raw_states = document["state"]
    if not isinstance(raw_states, list) or not raw_states:
        raise ValueError("registry must contain at least one [[state]] row")
    states: list[StateRow] = []
    expected_keys = {
        "rust_variant",
        "producer_kind",
        "semantic_state",
        "id_start",
        "id_end_exclusive",
    }
    for index, raw in enumerate(raw_states):
        if not isinstance(raw, dict) or set(raw) != expected_keys:
            raise ValueError(f"state[{index}] must contain exactly {sorted(expected_keys)}")
        row = StateRow(**raw)
        if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", row.rust_variant):
            raise ValueError(f"state[{index}].rust_variant must be UpperCamelCase")
        if not re.fullmatch(r"[a-z][a-z0-9_]*", row.producer_kind):
            raise ValueError(f"state[{index}].producer_kind must be snake_case")
        if not re.fullmatch(r"[a-z][a-z0-9_.]*", row.semantic_state):
            raise ValueError(f"state[{index}].semantic_state must be dotted snake_case")
        if row.id_start < 0 or row.id_end_exclusive <= row.id_start:
            raise ValueError(f"state[{index}] has an invalid id range")
        states.append(row)

    variants = [row.rust_variant for row in states]
    mappings = [(row.producer_kind, row.semantic_state) for row in states]
    if len(set(variants)) != len(variants):
        raise ValueError("registry rust_variant values must be unique")
    if len(set(mappings)) != len(mappings):
        raise ValueError("registry producer/state mappings must be unique")
    ordered = sorted(states, key=lambda row: row.id_start)
    cursor = 0
    for row in ordered:
        if row.id_start != cursor:
            raise ValueError("registry state id ranges must be contiguous and non-overlapping")
        cursor = row.id_end_exclusive
    if cursor != family_capacity:
        raise ValueError("registry state id ranges must exactly cover family.capacity")
    return Registry(family_name, family_capacity, tuple(ordered))


def render_registry(registry: Registry) -> str:
    lines = [
        "// @generated by scripts/verify_bolt_v3_evidence_novelty.py from",
        "// config/evidence-novelty.toml. Do not edit.",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum EvidenceStateOwner {",
    ]
    lines.extend(f"    {row.rust_variant}," for row in registry.states)
    lines.extend(
        [
            "}",
            "",
            "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
            "pub struct EvidenceStateRegistration {",
            "    pub owner: EvidenceStateOwner,",
            "    pub family: &'static str,",
            "    pub producer_kind: &'static str,",
            "    pub semantic_state: &'static str,",
            "    pub id_start: usize,",
            "    pub state_capacity: usize,",
            "}",
            "",
            f"pub const EVIDENCE_NOVELTY_OWNED_STATE_CAPACITY: usize = {registry.family_capacity};",
            "",
            "pub const EVIDENCE_STATE_REGISTRATIONS: &[EvidenceStateRegistration] = &[",
        ]
    )
    for row in registry.states:
        lines.extend(
            [
                "    EvidenceStateRegistration {",
                f"        owner: EvidenceStateOwner::{row.rust_variant},",
                f"        family: {json.dumps(registry.family_name)},",
                f"        producer_kind: {json.dumps(row.producer_kind)},",
                f"        semantic_state: {json.dumps(row.semantic_state)},",
                f"        id_start: {row.id_start},",
                f"        state_capacity: {row.capacity},",
                "    },",
            ]
        )
    lines.extend(
        [
            "];",
            "",
            "pub const fn evidence_state_registration(",
            "    owner: EvidenceStateOwner,",
            ") -> &'static EvidenceStateRegistration {",
            "    match owner {",
        ]
    )
    for index, row in enumerate(registry.states):
        lines.append(
            f"        EvidenceStateOwner::{row.rust_variant} => &EVIDENCE_STATE_REGISTRATIONS[{index}],"
        )
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def verification_findings(root: pathlib.Path) -> list[str]:
    findings: list[str] = []
    try:
        registry = load_registry(root / REGISTRY_PATH)
    except (OSError, ValueError, tomllib.TOMLDecodeError) as error:
        return [f"{REGISTRY_PATH}: {error}"]
    expected = render_registry(registry)
    try:
        actual = (root / GENERATED_PATH).read_text(encoding="utf-8")
    except OSError as error:
        findings.append(f"{GENERATED_PATH}: {error}")
    else:
        if actual != expected:
            findings.append(f"{GENERATED_PATH}: generated bytes do not match {REGISTRY_PATH}")

    producer_text = (root / PRODUCER_PATH).read_text(encoding="utf-8")
    referenced = set(re.findall(r"EvidenceStateOwner::([A-Z][A-Za-z0-9]*)", producer_text))
    registered = {row.rust_variant for row in registry.states}
    if referenced != registered:
        findings.append(
            f"{PRODUCER_PATH}: producer owner references {sorted(referenced)} "
            f"must equal registered owners {sorted(registered)}"
        )
    if ".record_strategy_input_snapshot(&strategy_input_snapshot)" not in producer_text:
        findings.append(f"{PRODUCER_PATH}: submit-linked strategy snapshot path must remain direct")
    entry_match = re.search(
        r"fn record_entry_skip_once\(.*?\n    \}\n\n    fn ", producer_text, re.S
    )
    if entry_match is None:
        findings.append(f"{PRODUCER_PATH}: record_entry_skip_once function missing")
    else:
        body = entry_match.group(0)
        try:
            claim = body.index("entry_skip_novelty.claim_once")
            fields = body.index("entry_evaluation_log_fields_at")
            payload = body.index("BoltV3EntrySkipEvidence::from_entry_skip")
            append = body.index(".record_entry_skip(&evidence)")
        except ValueError:
            findings.append(f"{PRODUCER_PATH}: entry-skip novelty/payload/append seam incomplete")
        else:
            if not claim < fields < payload < append:
                findings.append(
                    f"{PRODUCER_PATH}: entry-skip duplicate claim must precede fields, payload, and append"
                )
    blocked_match = re.search(
        r"fn record_blocked_entry_strategy_input_snapshot_once\(.*?\n    \}\n\n    fn ",
        producer_text,
        re.S,
    )
    if blocked_match is None:
        findings.append(f"{PRODUCER_PATH}: blocked strategy-input producer function missing")
    else:
        body = blocked_match.group(0)
        try:
            claim = body.index("blocked_strategy_input_novelty")
            payload = body.index("blocked_entry_strategy_input_evidence_snapshot_at")
            append = body.index(".record_strategy_input_snapshot(&snapshot)")
        except ValueError:
            findings.append(f"{PRODUCER_PATH}: blocked snapshot novelty/payload/append seam incomplete")
        else:
            if not claim < payload < append:
                findings.append(
                    f"{PRODUCER_PATH}: blocked snapshot duplicate claim must precede payload and append"
                )

    novelty_text = (root / NOVELTY_PATH).read_text(encoding="utf-8")
    match = re.search(r"pub struct EvidenceEpisodeParts \{(?P<body>.*?)\n\}", novelty_text, re.S)
    if match is None:
        findings.append(f"{NOVELTY_PATH}: EvidenceEpisodeParts declaration missing")
    else:
        forbidden = (
            "price",
            "timestamp",
            "time_",
            "age",
            "counter",
            "flag",
            "diagnostic",
            "slug",
            "retry",
            "schema",
            "config",
            "deployment",
        )
        body = match.group("body").lower()
        present = sorted(term for term in forbidden if term in body)
        if present:
            findings.append(f"{NOVELTY_PATH}: episode parts contain forbidden terms {present}")
    return findings


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path, default=REPO_ROOT)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    if args.write:
        registry = load_registry(root / REGISTRY_PATH)
        (root / GENERATED_PATH).write_text(render_registry(registry), encoding="utf-8")
        return 0
    findings = verification_findings(root)
    if findings:
        for finding in findings:
            print(f"ERROR: {finding}", file=sys.stderr)
        return 1
    print("OK: evidence novelty registry and producer mappings are closed.")
    return 0


if __name__ == "__main__":
    import lane_governor

    lane_governor.acquire()
    raise SystemExit(main())
