[source]
git = "https://github.com/nautechsystems/nautilus_trader.git"
revision = "d81be0bcc7a473c45d2dc8a8885638336073a218"

[binance_spot_sbe]
schema_3_5 = true
adapter_receive_clock = true
new_risk_quorum = true
