// @generated by scripts/verify_bolt_v3_evidence_novelty.py from
// config/evidence-novelty.toml. Do not edit.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EvidenceStateOwner {
    EntrySkip,
    BlockedStrategyInputSnapshot,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EvidenceStateRegistration {
    pub owner: EvidenceStateOwner,
    pub family: &'static str,
    pub producer_kind: &'static str,
    pub semantic_state: &'static str,
    pub id_start: usize,
    pub state_capacity: usize,
}

pub const EVIDENCE_NOVELTY_OWNED_STATE_CAPACITY: usize = 256;

pub const EVIDENCE_STATE_REGISTRATIONS: &[EvidenceStateRegistration] = &[
    EvidenceStateRegistration {
        owner: EvidenceStateOwner::EntrySkip,
        family: "market",
        producer_kind: "entry_skip",
        semantic_state: "entry_skip.semantic",
        id_start: 0,
        state_capacity: 128,
    },
    EvidenceStateRegistration {
        owner: EvidenceStateOwner::BlockedStrategyInputSnapshot,
        family: "market",
        producer_kind: "strategy_input_snapshot",
        semantic_state: "strategy_input_snapshot.blocked_rv",
        id_start: 128,
        state_capacity: 128,
    },
];

pub const fn evidence_state_registration(
    owner: EvidenceStateOwner,
) -> &'static EvidenceStateRegistration {
    match owner {
        EvidenceStateOwner::EntrySkip => &EVIDENCE_STATE_REGISTRATIONS[0],
        EvidenceStateOwner::BlockedStrategyInputSnapshot => &EVIDENCE_STATE_REGISTRATIONS[1],
    }
}
