//! Tracked production-profile → runtime `live.toml` generation and verification (issue #768).
//!
//! ## Problem this closes
//!
//! The live runtime config (`config/live.toml`) and its operator source
//! (`config/live.local.toml`) were gitignored and hand-maintained. They were
//! therefore invisible to CI and drifted silently against the deployed binary's
//! schema. On 2026-06-18 a BTC pilot start failed at `systemd` time because the
//! hand-edited config carried a stale key (`nautilus.data_engine
//! .graceful_shutdown_on_error`) the current binary no longer accepts — and
//! hash parity between local and EC2 did not catch it, because both copies were
//! equally stale.
//!
//! ## Single, fail-closed path
//!
//! The fix makes the production config a *tracked* artifact (`config/prod-btc-5m
//! .toml`) and gives it one generation + verification path:
//!
//! * [`generate_live_config`] loads the tracked profile through the SAME
//!   [`load_bolt_v3_config`] the binary uses at startup, enforces the production
//!   invariants a live deploy requires (loss rails present AND enabled — disabled
//!   rails are inert at runtime — and a non-empty strategy selection), and emits a
//!   deterministic, provenance-stamped runtime config. Any schema, semantic, or
//!   invariant error fails the generation closed.
//! * [`verify_live_config`] re-generates from the approved profile and proves a
//!   deployed runtime config is (a) byte-identical to the regenerated artifact,
//!   (b) still loads against this exact binary, and (c) has strategy files whose
//!   contents match the approved profile's (strategy_files are referenced by path,
//!   so they are not in the byte-compared root body). Byte parity alone is
//!   insufficient — the independent load catches schema staleness.
//!
//! `verify_live_config` covers the config-identity half of pre-arm. The full
//! pre-arm gate chains it with live secret resolution and the no-submit/readiness
//! check: `generate-live-config` → `verify-live-config` → `secrets resolve` →
//! `ops prestart-check` (see `deploy/README.md`). The single source of truth is
//! the tracked profile; `config/root.toml` is the multi-asset template and owns
//! the shared infrastructure blocks (a test fails CI if the profile drifts from it).
//! The production systemd unit runs `verify-live-config` as `ExecStartPre`, so the
//! gate is enforced at the live entry point, not advisory. `verify` proves the
//! deployed config regenerates from the on-box profile and that the production
//! invariants hold; establishing that the on-box profile is the reviewed Git
//! revision is the deploy process's responsibility (deploy from the reviewed
//! checkout), with a release-digest anchor tracked as a follow-up.
//!
//! The profile is itself a complete [`BoltV3RootConfig`], so schema currency is
//! enforced by the real parser (`#[serde(deny_unknown_fields)]`), not a parallel
//! one — there is no second config format and no second code path. The
//! provenance header is emitted as TOML *comments* for exactly this reason:
//! a non-comment metadata key would be rejected by `deny_unknown_fields`.

use std::path::{Path, PathBuf};

use crate::bolt_v3_config::{BoltV3ConfigError, LoadedBoltV3Config, load_bolt_v3_config};

/// Bump when the provenance header format changes in a way that alters the
/// generated bytes. The version is part of the header so a deployed artifact
/// generated by an older binary fails byte-equality against a newer generator
/// and is regenerated rather than silently trusted.
pub const GENERATOR_FORMAT_VERSION: u32 = 1;

/// First line of every generated runtime config. `verify_live_config` and the
/// `generate` guard match on this exact prefix.
pub const GENERATED_MARKER_PREFIX: &str = "# bolt-v2:generated-live-config format=";

/// Outcome of generating a runtime config from a tracked profile.
#[derive(Debug, Clone, serde::Serialize)]
pub struct GeneratedLiveConfig {
    /// Relative file name of the source profile (e.g. `prod-btc-5m.toml`).
    pub source_profile: String,
    /// `config_bundle_checksum` of the loaded profile (root text + strategy
    /// files). Recorded in the header and reproducible from the profile alone.
    pub profile_bundle_sha256: String,
    /// Production invariants confirmed before generation.
    pub invariants: ProductionInvariants,
    /// Full runtime config text: provenance header (comments) + profile body.
    pub text: String,
}

/// Result of verifying a deployed runtime config against its source profile.
#[derive(Debug, Clone, serde::Serialize)]
pub struct LiveConfigVerification {
    pub profile_path: PathBuf,
    pub deployed_path: PathBuf,
    pub profile_bundle_sha256: String,
    /// Production invariants re-confirmed on the *deployed* file.
    pub invariants: ProductionInvariants,
    /// True once byte-equality and the independent binary load both passed.
    pub matches_profile: bool,
    pub loads_against_binary: bool,
}

/// The production-readiness facts `generate`/`verify` confirm and report. Values
/// (e.g. the loss-rail amounts, which strategy is selected) are decided by the
/// profile and the pilot-config issues, not by this module — it only proves the
/// rails and selection are present and fails closed when they are not.
#[derive(Debug, Clone, serde::Serialize)]
pub struct ProductionInvariants {
    pub strategy_files: Vec<String>,
    pub loss_governor_present: bool,
    pub loss_governor_enabled: bool,
    pub max_per_trade_loss: String,
    pub max_daily_loss: String,
    pub max_rolling_loss: String,
    pub max_drawdown: String,
    pub default_max_notional_per_order: String,
}

/// Errors from generating or verifying a runtime config. All are fail-closed:
/// generation and verification only succeed when every check passes.
#[derive(Debug)]
pub enum ProfileError {
    /// The profile (or deployed file) did not load against this binary's schema
    /// + semantic validation. This is the staleness guard.
    Load {
        path: PathBuf,
        source: BoltV3ConfigError,
    },
    /// Filesystem error reading a profile or deployed file.
    Io { path: PathBuf, message: String },
    /// A required production invariant was missing (e.g. no loss rails).
    Invariant(String),
    /// A deployed file did not match the config regenerated from the profile.
    Mismatch(String),
    /// `generate` was pointed at a file that is itself already a generated
    /// runtime config rather than a source profile.
    AlreadyGenerated(PathBuf),
}

impl std::fmt::Display for ProfileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProfileError::Load { path, source } => {
                write!(
                    f,
                    "config `{}` does not load against this binary: {source}",
                    path.display()
                )
            }
            ProfileError::Io { path, message } => {
                write!(f, "failed to read `{}`: {message}", path.display())
            }
            ProfileError::Invariant(message) => write!(f, "{message}"),
            ProfileError::Mismatch(message) => write!(f, "{message}"),
            ProfileError::AlreadyGenerated(path) => write!(
                f,
                "`{}` is already a generated runtime config; pass the source profile instead",
                path.display()
            ),
        }
    }
}

impl std::error::Error for ProfileError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ProfileError::Load { source, .. } => Some(source),
            _ => None,
        }
    }
}

fn read_config_text(path: &Path) -> Result<String, ProfileError> {
    crate::bounded_config_read::read_to_string(path).map_err(|source| ProfileError::Io {
        path: path.to_path_buf(),
        message: source.to_string(),
    })
}

fn profile_basename(path: &Path) -> String {
    path.file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_else(|| path.to_string_lossy().into_owned())
}

/// Confirm the production invariants the live deploy depends on, failing closed
/// when any is absent. Reused by both generation (on the profile) and
/// verification (on the deployed file).
fn confirm_production_invariants(
    loaded: &LoadedBoltV3Config,
) -> Result<ProductionInvariants, ProfileError> {
    if loaded.root.strategy_files.is_empty() {
        return Err(ProfileError::Invariant(
            "production profile declares no strategy_files".to_string(),
        ));
    }

    let governor = loaded.root.risk.loss_governor.as_ref().ok_or_else(|| {
        ProfileError::Invariant(
            "production profile must declare [risk.loss_governor] loss rails before live deploy"
                .to_string(),
        )
    })?;

    if !governor.enabled {
        return Err(ProfileError::Invariant(
            "[risk.loss_governor].enabled must be true before live deploy — present-but-disabled \
             rails are inert at runtime (loss_governor_policy_from_loaded returns None when \
             disabled, so no loss-governor policy is constructed)"
                .to_string(),
        ));
    }

    let max_per_trade_loss = governor.max_per_trade_loss.clone().ok_or_else(|| {
        ProfileError::Invariant(
            "[risk.loss_governor].max_per_trade_loss must be set before live deploy".to_string(),
        )
    })?;
    let max_daily_loss = governor.max_daily_loss.clone().ok_or_else(|| {
        ProfileError::Invariant(
            "[risk.loss_governor].max_daily_loss must be set before live deploy".to_string(),
        )
    })?;
    let max_rolling_loss = governor.max_rolling_loss.clone().ok_or_else(|| {
        ProfileError::Invariant(
            "[risk.loss_governor].max_rolling_loss must be set before live deploy".to_string(),
        )
    })?;
    let max_drawdown = governor.max_drawdown.clone().ok_or_else(|| {
        ProfileError::Invariant(
            "[risk.loss_governor].max_drawdown must be set before live deploy".to_string(),
        )
    })?;

    Ok(ProductionInvariants {
        strategy_files: loaded.root.strategy_files.clone(),
        loss_governor_present: true,
        loss_governor_enabled: governor.enabled,
        max_per_trade_loss,
        max_daily_loss,
        max_rolling_loss,
        max_drawdown,
        default_max_notional_per_order: loaded.root.risk.default_max_notional_per_order.clone(),
    })
}

fn provenance_header(source_profile: &str, profile_bundle_sha256: &str) -> String {
    format!(
        "{GENERATED_MARKER_PREFIX}{GENERATOR_FORMAT_VERSION}\n\
         # source_profile={source_profile}\n\
         # profile_bundle_sha256={profile_bundle_sha256}\n\
         # Generated by `bolt-v2 ops generate-live-config`; DO NOT EDIT.\n\
         # Edit the tracked source profile in a reviewed PR, then regenerate (issue #768).\n\
         \n"
    )
}

/// Generate a deterministic, provenance-stamped runtime config from a tracked
/// production profile. Fails closed on any schema, semantic, or
/// production-invariant problem in the profile.
pub fn generate_live_config(profile_path: &Path) -> Result<GeneratedLiveConfig, ProfileError> {
    let profile_text = read_config_text(profile_path)?;
    if profile_text.contains(GENERATED_MARKER_PREFIX) {
        return Err(ProfileError::AlreadyGenerated(profile_path.to_path_buf()));
    }

    let loaded = load_bolt_v3_config(profile_path).map_err(|source| ProfileError::Load {
        path: profile_path.to_path_buf(),
        source,
    })?;
    let invariants = confirm_production_invariants(&loaded)?;

    let source_profile = profile_basename(profile_path);
    let header = provenance_header(&source_profile, &loaded.config_bundle_checksum);
    let text = format!("{header}{profile_text}");

    Ok(GeneratedLiveConfig {
        source_profile,
        profile_bundle_sha256: loaded.config_bundle_checksum,
        invariants,
        text,
    })
}

/// Verify that a deployed runtime config is exactly what the approved profile
/// generates AND still loads against this binary. Both must hold.
pub fn verify_live_config(
    profile_path: &Path,
    deployed_path: &Path,
) -> Result<LiveConfigVerification, ProfileError> {
    let generated = generate_live_config(profile_path)?;
    let deployed_text = read_config_text(deployed_path)?;

    if deployed_text != generated.text {
        return Err(ProfileError::Mismatch(format!(
            "deployed runtime config `{}` does not match the config generated from profile `{}`; \
             re-run `ops generate-live-config` and redeploy rather than hand-editing",
            deployed_path.display(),
            profile_path.display()
        )));
    }

    // Independently load the deployed file through the binary. Byte-equality
    // proves provenance; this proves the bytes still satisfy the live schema.
    let deployed_loaded =
        load_bolt_v3_config(deployed_path).map_err(|source| ProfileError::Load {
            path: deployed_path.to_path_buf(),
            source,
        })?;
    let invariants = confirm_production_invariants(&deployed_loaded)?;

    // The byte-equality above pins the root body, but strategy_files are referenced
    // by relative path and resolved at the deploy site — their CONTENTS are not part
    // of the compared bytes. Compare them explicitly so a divergent deployed strategy
    // file (valid schema, but different sizing/feeds/stale) cannot pass as approved.
    let profile_loaded =
        load_bolt_v3_config(profile_path).map_err(|source| ProfileError::Load {
            path: profile_path.to_path_buf(),
            source,
        })?;
    if profile_loaded.strategies.len() != deployed_loaded.strategies.len() {
        return Err(ProfileError::Mismatch(format!(
            "deployed runtime config references {} strategy file(s) but must match the profile's {}",
            deployed_loaded.strategies.len(),
            profile_loaded.strategies.len()
        )));
    }
    for (approved, deployed) in profile_loaded
        .strategies
        .iter()
        .zip(deployed_loaded.strategies.iter())
    {
        if approved.relative_path != deployed.relative_path {
            return Err(ProfileError::Mismatch(format!(
                "deployed strategy path `{}` must match the approved `{}`",
                deployed.relative_path, approved.relative_path
            )));
        }
        let approved_text = read_config_text(&approved.config_path)?;
        let deployed_strategy_text = read_config_text(&deployed.config_path)?;
        if approved_text != deployed_strategy_text {
            return Err(ProfileError::Mismatch(format!(
                "deployed strategy `{}` must match the tracked profile's copy; redeploy the \
                 strategy files alongside the generated runtime config",
                deployed.relative_path
            )));
        }
    }

    Ok(LiveConfigVerification {
        profile_path: profile_path.to_path_buf(),
        deployed_path: deployed_path.to_path_buf(),
        profile_bundle_sha256: generated.profile_bundle_sha256,
        invariants,
        matches_profile: true,
        loads_against_binary: true,
    })
}
