// @generated by scripts/generate_risk_closure_workspace_config.py from risk-closure-workspaces.toml.
// Do not edit this file directly.

const RISK_CLOSURE_WORKSPACE_CONFIG: RiskClosureWorkspaceConfig =
    RiskClosureWorkspaceConfig {
        arena_bytes: 167772160,
        slot_bytes: 16777216,
        capacity: 10,
        production_activation_enabled: false,
    };
