pub mod bolt_v3_adapters;
pub mod bolt_v3_archetypes;
pub mod bolt_v3_atomic_io;
pub mod bolt_v3_basket_admission;
pub mod bolt_v3_basket_execution;
pub mod bolt_v3_basket_store;
pub mod bolt_v3_binary_outcome_edge;
pub mod bolt_v3_book_sizing;
pub mod bolt_v3_capital_reservation;
pub mod bolt_v3_client_registration;
pub mod bolt_v3_config;
pub mod bolt_v3_decision_evidence;
pub mod bolt_v3_executable_cost;
pub mod bolt_v3_fair_value_pricing;
pub mod bolt_v3_instrument_filters;
mod bolt_v3_instrument_metadata_bus;
pub mod bolt_v3_iv;
pub mod bolt_v3_kill_switch;
pub mod bolt_v3_kill_switch_store;
pub mod bolt_v3_live_node;
pub mod bolt_v3_loss_governor;
pub mod bolt_v3_loss_halt_actions;
pub mod bolt_v3_loss_runtime_feed;
pub mod bolt_v3_maker_event_fence;
pub mod bolt_v3_maker_inventory;
pub mod bolt_v3_maker_microprice;
pub mod bolt_v3_maker_model;
pub mod bolt_v3_maker_reservation;
pub mod bolt_v3_market_families;
pub mod bolt_v3_numeric;
mod bolt_v3_observed_dedupe;
pub mod bolt_v3_operator_artifacts;
pub mod bolt_v3_order_execution;
pub mod bolt_v3_order_intent;
pub mod bolt_v3_outcome_group_hyperliquid;
pub mod bolt_v3_outcome_group_polymarket;
pub mod bolt_v3_outcome_group_scanner;
pub mod bolt_v3_outcome_group_sources;
pub mod bolt_v3_outcome_groups;
pub mod bolt_v3_position_contract;
pub mod bolt_v3_position_sizer;
pub mod bolt_v3_position_sizer_runtime_feed;
pub mod bolt_v3_providers;
pub mod bolt_v3_quote_lifecycle;
pub mod bolt_v3_quoting;
pub mod bolt_v3_readiness;
pub mod bolt_v3_realized_volatility;
pub mod bolt_v3_realized_volatility_runtime;
pub mod bolt_v3_reference_price;
pub mod bolt_v3_reference_price_health;
// Re-exported at crate root so backtesting consumers can name these
// reconstruction types without writing the snake_case module path. The
// backtesting-vertical-slice sample-venue source fence forbids the literal
// "reference_price" token in its production Rust; the CamelCase type names are
// fence-clean, the module path is not.
pub use bolt_v3_reference_price::{ReferencePriceUpdate, ReferenceQuoteProvenance};
pub mod bolt_v3_requote_budget;
pub mod bolt_v3_secrets;
pub mod bolt_v3_sizing;
pub mod bolt_v3_sizing_state;
pub mod bolt_v3_source_integrity;
pub mod bolt_v3_strategy_registration;
pub mod bolt_v3_submit_admission;
pub mod bolt_v3_taker_pricing;
pub mod bolt_v3_taker_updown_signal;
pub mod bolt_v3_trade_flow;
pub mod bolt_v3_validate;
mod bounded_config_read;
pub mod execution_state;
pub mod lake_batch;
pub mod log_sweep;
pub mod nt_runtime_capture;
pub mod raw_types;
pub mod secrets;
pub mod shadow_pnl;
pub mod source_canonicalization;
pub mod strategies;
pub mod strategy_runtime_bindings;
pub mod venue_contract;
